from __future__ import annotations

from typing import Any

CHAIN_LAYERS = [
    "自然资源",
    "公共品与能源",
    "基础材料",
    "通用零部件",
    "设备与系统",
    "终端产品",
    "渠道与服务",
    "回收与再生产",
]


def _company(name: str, ticker: str | None = None, market: str | None = None, role: str | None = None) -> dict[str, Any]:
    row: dict[str, Any] = {"name": name}
    if ticker:
        row["ticker"] = ticker
    if market:
        row["market"] = market
    if role:
        row["role"] = role
    return row


def _indicator(name: str, indicator_type: str, code: str | None = None, weight: float | None = None) -> dict[str, Any]:
    row: dict[str, Any] = {"name": name, "type": indicator_type}
    if code:
        row["code"] = code
    if weight is not None:
        row["weight"] = weight
    return row


def _node(
    node_key: str,
    name: str,
    layer: str,
    node_type: str,
    description: str,
    industry_names: list[str],
    tags: list[str],
    anchor_companies: list[dict[str, Any]],
    indicators: list[dict[str, Any]],
) -> dict[str, Any]:
    return {
        "node_key": node_key,
        "name": name,
        "layer": layer,
        "node_type": node_type,
        "description": description,
        "industry_names": industry_names,
        "tags": tags,
        "anchor_companies": anchor_companies,
        "indicators": indicators,
    }


def _edge(source: str, target: str, relation_type: str, flow: str, weight: float) -> dict[str, Any]:
    return {
        "source": source,
        "target": target,
        "relation_type": relation_type,
        "flow": flow,
        "weight": weight,
    }


def _region(
    region_key: str,
    label: str,
    x: float,
    y: float,
    geo_role: str,
    specialty: str,
    node_keys: list[str],
    listed_hubs: list[str],
) -> dict[str, Any]:
    return {
        "region_key": region_key,
        "label": label,
        "x": x,
        "y": y,
        "geo_role": geo_role,
        "specialty": specialty,
        "node_keys": node_keys,
        "listed_hubs": listed_hubs,
    }


CHAIN_NODES = [
    _node(
        "coal",
        "煤炭",
        "自然资源",
        "resource",
        "动力煤、焦煤与煤化工原料，是火电和高温工业的重要成本锚。",
        ["煤炭", "电力电网", "化工材料"],
        ["energy", "bulk", "fuel"],
        [_company("中国神华", "601088", "CN", "动力煤一体化"), _company("Peabody Energy", "BTU", "US", "海运煤")],
        [_indicator("秦皇岛动力煤价格", "price", "QHD_COAL", 0.55), _indicator("沿海电厂煤耗天数", "inventory", "COAL_DAYS", 0.45)],
    ),
    _node(
        "crude_oil",
        "原油",
        "自然资源",
        "resource",
        "全球原油供给与库存决定炼化利润、运输燃料和石化原料成本。",
        ["油气", "化工材料", "航运港口"],
        ["energy", "global", "benchmark"],
        [_company("Saudi Aramco", role="原油供给龙头"), _company("埃克森美孚", "XOM", "US", "国际油气综合体")],
        [_indicator("Brent 原油价格", "price", "BRENT", 0.6), _indicator("OECD 原油库存", "inventory", "OECD_OIL_STOCK", 0.4)],
    ),
    _node(
        "natural_gas",
        "天然气",
        "自然资源",
        "resource",
        "天然气兼具化工原料与发电燃料属性，直接影响 LNG、气电和化肥链。",
        ["油气", "电力电网", "化工材料"],
        ["energy", "cleaner-fuel", "feedstock"],
        [_company("Cheniere Energy", "LNG", "US", "LNG 出口"), _company("中国海油", "600938", "CN", "国内气源")],
        [_indicator("JKM LNG 价格", "price", "JKM_LNG", 0.5), _indicator("Henry Hub 天然气价格", "price", "HENRY_HUB", 0.5)],
    ),
    _node(
        "iron_ore",
        "铁矿石",
        "自然资源",
        "resource",
        "铁矿石决定长流程钢厂成本，是钢铁、工程机械和建筑链的先导变量。",
        ["钢铁", "工程机械", "建筑建材"],
        ["bulk", "ferrous", "construction"],
        [_company("力拓", "RIO", "US", "主流矿山"), _company("Vale", "VALE", "US", "高品位铁矿")],
        [_indicator("62% 铁矿石指数", "price", "IO62", 0.65), _indicator("港口铁矿库存", "inventory", "IRON_PORT_STOCK", 0.35)],
    ),
    _node(
        "copper_ore",
        "铜矿",
        "自然资源",
        "resource",
        "铜矿供给约束决定精铜成本，贯穿电网、通信、AI 服务器和新能源设备。",
        ["有色金属", "电力电网", "通信设备"],
        ["nonferrous", "electrification", "grid"],
        [_company("Freeport-McMoRan", "FCX", "US", "大型铜矿"), _company("紫金矿业", "601899", "CN", "全球化铜金矿")],
        [_indicator("LME 铜价", "price", "LME_CU", 0.6), _indicator("全球铜精矿 TC/RC", "margin", "CU_TCRC", 0.4)],
    ),
    _node(
        "bauxite",
        "铝土矿",
        "自然资源",
        "resource",
        "铝土矿与氧化铝供给影响电解铝成本，对轻量化和光伏边框敏感。",
        ["有色金属", "光伏", "新能源车"],
        ["nonferrous", "lightweight", "solar"],
        [_company("中国铝业", "601600", "CN", "铝产业链"), _company("Alcoa", "AA", "US", "氧化铝与电解铝")],
        [_indicator("氧化铝价格", "price", "ALUMINA", 0.5), _indicator("电解铝利润", "margin", "AL_MARGIN", 0.5)],
    ),
    _node(
        "lithium_ore",
        "锂资源",
        "自然资源",
        "resource",
        "盐湖与锂辉石资源决定锂盐价格，是动力电池和储能景气的核心变量。",
        ["有色金属", "储能", "新能源车"],
        ["battery", "critical-mineral", "energy-storage"],
        [_company("赣锋锂业", "002460", "CN", "锂资源与锂盐"), _company("Albemarle", "ALB", "US", "全球锂资源")],
        [_indicator("电池级碳酸锂价格", "price", "LI_CARBONATE", 0.7), _indicator("锂辉石精矿价格", "price", "SPODUMENE", 0.3)],
    ),
    _node(
        "nickel_ore",
        "镍资源",
        "自然资源",
        "resource",
        "红土镍矿和高冰镍供给影响三元材料成本，也影响不锈钢和高温合金。",
        ["有色金属", "储能", "新能源车"],
        ["battery", "stainless", "critical-mineral"],
        [_company("Vale Indonesia", role="红土镍矿"), _company("青山控股", role="镍铁与高冰镍")],
        [_indicator("LME 镍价", "price", "LME_NI", 0.55), _indicator("印尼镍生铁产量", "supply", "INDO_NPI", 0.45)],
    ),
    _node(
        "rare_earth_ore",
        "稀土资源",
        "自然资源",
        "resource",
        "轻重稀土与磁材原料对永磁电机、机器人、风电和智能驾驶均有约束。",
        ["稀土", "机器人", "智能驾驶"],
        ["critical-mineral", "magnet", "motor"],
        [_company("北方稀土", "600111", "CN", "轻稀土龙头"), _company("Lynas", "LYC", "AU", "海外稀土")],
        [_indicator("氧化镨钕价格", "price", "NDPR", 0.6), _indicator("稀土配额", "policy", "RARE_EARTH_QUOTA", 0.4)],
    ),
    _node(
        "potash_phosphate",
        "钾肥与磷矿",
        "自然资源",
        "resource",
        "钾肥、磷矿和磷化工连接农业种植、饲料和基础化工成本。",
        ["化工材料", "食品饮料", "农业"],
        ["fertilizer", "agriculture", "crop-input"],
        [_company("Nutrien", "NTR", "US", "钾肥"), _company("云天化", "600096", "CN", "磷矿与磷肥")],
        [_indicator("氯化钾价格", "price", "POTASH", 0.5), _indicator("磷酸一铵价格", "price", "MAP", 0.5)],
    ),
    _node(
        "corn_soybean",
        "玉米与大豆",
        "自然资源",
        "resource",
        "粮油作物决定饲料、淀粉糖和植物蛋白成本，是食品饮料上游锚点。",
        ["食品饮料", "养殖", "农业"],
        ["agri", "feed", "food-input"],
        [_company("ADM", "ADM", "US", "全球粮商"), _company("中粮国际", role="粮油流通")],
        [_indicator("CBOT 玉米价格", "price", "CBOT_CORN", 0.5), _indicator("CBOT 大豆价格", "price", "CBOT_SOY", 0.5)],
    ),
    _node(
        "timber_pulp",
        "木材与纸浆",
        "自然资源",
        "resource",
        "木材、纸浆和林化资源影响包装纸、生活纸、板材和家居供应链。",
        ["包装造纸", "建筑建材", "商业零售"],
        ["forestry", "packaging", "consumer"],
        [_company("Suzano", "SUZ", "US", "纸浆"), _company("太阳纸业", "002078", "CN", "浆纸一体化")],
        [_indicator("阔叶浆价格", "price", "BHKP", 0.55), _indicator("木材期货价格", "price", "LUMBER", 0.45)],
    ),
    _node(
        "power_grid",
        "电力电网",
        "公共品与能源",
        "utility",
        "发电、输配电、特高压和配网自动化共同构成全产业链的公共底座。",
        ["电力电网", "储能", "AI算力"],
        ["grid", "utility", "infrastructure"],
        [_company("国家电网", role="特高压与配网投资"), _company("南方电网", role="区域电网运营")],
        [_indicator("全社会用电量", "demand", "POWER_DEMAND", 0.45), _indicator("电网投资完成额", "capex", "GRID_CAPEX", 0.55)],
    ),
    _node(
        "thermal_power",
        "火电",
        "公共品与能源",
        "utility",
        "煤电与气电承担调峰与基荷，在电价和容量电费机制下修复盈利。",
        ["电力电网", "煤炭", "油气"],
        ["power", "dispatch", "cashflow"],
        [_company("华能国际", "600011", "CN", "火电"), _company("Vistra", "VST", "US", "独立电力")],
        [_indicator("沿海电厂煤价联动", "spread", "COAL_POWER_SPREAD", 0.6), _indicator("火电利用小时", "utilization", "THERMAL_UTIL", 0.4)],
    ),
    _node(
        "nuclear_power",
        "核电",
        "公共品与能源",
        "utility",
        "核电提供低碳基荷电力，兼具长周期资产和装备国产化特征。",
        ["核电", "电力电网", "工程机械"],
        ["baseload", "low-carbon", "long-cycle"],
        [_company("中国广核", "003816", "CN", "核电运营"), _company("Constellation Energy", "CEG", "US", "核电资产")],
        [_indicator("核电利用小时", "utilization", "NUCLEAR_UTIL", 0.5), _indicator("核准机组数量", "policy", "NUCLEAR_APPROVAL", 0.5)],
    ),
    _node(
        "hydropower",
        "水电",
        "公共品与能源",
        "utility",
        "水电受来水和电价影响，是西南清洁电力与铝冶炼的重要支撑。",
        ["电力电网", "有色金属", "建筑建材"],
        ["renewable", "baseload", "regional"],
        [_company("长江电力", "600900", "CN", "大型水电"), _company("Brookfield Renewable", "BEP", "US", "全球水电资产")],
        [_indicator("来水偏离度", "hydrology", "HYDRO_INFLOW", 0.5), _indicator("水电利用小时", "utilization", "HYDRO_UTIL", 0.5)],
    ),
    _node(
        "solar_power",
        "光伏发电",
        "公共品与能源",
        "utility",
        "集中式与分布式光伏拉动硅料、组件、逆变器和储能需求。",
        ["光伏", "储能", "电力电网"],
        ["renewable", "solar", "distributed"],
        [_company("隆基绿能", "601012", "CN", "组件与电池"), _company("First Solar", "FSLR", "US", "薄膜组件")],
        [_indicator("组件价格", "price", "PV_MODULE", 0.45), _indicator("国内新增装机", "demand", "PV_INSTALL", 0.55)],
    ),
    _node(
        "wind_power",
        "风电",
        "公共品与能源",
        "utility",
        "陆风与海风带动轴承、铸锻件、海缆和整机需求，订单波动较强。",
        ["风电", "电力电网", "工程机械"],
        ["renewable", "offshore", "equipment"],
        [_company("金风科技", "002202", "CN", "风机"), _company("Vestas", "VWDRY", "US", "全球风机")],
        [_indicator("风机招标价格", "price", "WIND_TENDER", 0.45), _indicator("新增装机", "demand", "WIND_INSTALL", 0.55)],
    ),
    _node(
        "lng_gas",
        "LNG 与燃气",
        "公共品与能源",
        "utility",
        "LNG 接收站、城燃和工业燃气连接全球气价与本地能源负荷。",
        ["油气", "电力电网", "物流快递"],
        ["gas", "city-gas", "import"],
        [_company("新奥股份", "600803", "CN", "城燃与 LNG"), _company("Tokyo Gas", role="城市燃气")],
        [_indicator("国内 LNG 出厂价", "price", "CN_LNG", 0.55), _indicator("LNG 接收站利用率", "utilization", "LNG_UTIL", 0.45)],
    ),
    _node(
        "refinery_fuels",
        "炼化与成品油",
        "公共品与能源",
        "utility",
        "炼油、乙烯裂解和成品油分销同时服务化工链与交通运输。",
        ["油气", "化工材料", "航运港口"],
        ["refining", "transport", "petchem"],
        [_company("中国石化", "600028", "CN", "炼化一体化"), _company("Valero", "VLO", "US", "炼油")],
        [_indicator("汽柴油裂解价差", "margin", "REFINING_SPREAD", 0.6), _indicator("开工率", "utilization", "REFINERY_RUN", 0.4)],
    ),
    _node(
        "water_utility",
        "水务与工业用水",
        "公共品与能源",
        "utility",
        "供水、污水和超纯水系统是半导体、生物制造和城市运行的基础设施。",
        ["环保水务", "半导体", "建筑建材"],
        ["water", "utility", "city"],
        [_company("首创环保", "600008", "CN", "水务"), _company("Veolia", role="水务服务")],
        [_indicator("工业水价", "price", "INDUSTRIAL_WATER", 0.45), _indicator("污水处理量", "demand", "WASTE_WATER", 0.55)],
    ),
    _node(
        "petrochemicals",
        "石化原料",
        "基础材料",
        "material",
        "乙烯、丙烯、芳烃等石化平台是塑料、化纤和电子化学品的起点。",
        ["化工材料", "纺织服饰", "包装造纸"],
        ["petchem", "feedstock", "chain-core"],
        [_company("恒力石化", "600346", "CN", "炼化一体化"), _company("LyondellBasell", "LYB", "US", "烯烃与聚烯烃")],
        [_indicator("乙烯价差", "margin", "OLEFIN_SPREAD", 0.5), _indicator("PX-PTA 价差", "margin", "PX_PTA", 0.5)],
    ),
    _node(
        "specialty_chemicals",
        "精细化工与电子化学品",
        "基础材料",
        "material",
        "氟化工、光刻胶、溶剂、胶黏剂和添加剂向新能源、半导体和医药延伸。",
        ["化工材料", "半导体", "创新药"],
        ["specialty", "electronic-chemicals", "high-margin"],
        [_company("万华化学", "600309", "CN", "平台型化工"), _company("JSR", role="光刻胶材料")],
        [_indicator("电子化学品价格指数", "price", "ELE_CHEM", 0.45), _indicator("化工品开工率", "utilization", "CHEM_UTIL", 0.55)],
    ),
    _node(
        "plastics_rubber",
        "塑料橡胶",
        "基础材料",
        "material",
        "工程塑料、改性塑料、橡胶和弹性体广泛用于汽车、家电和消费包装。",
        ["化工材料", "汽车零部件", "家电"],
        ["polymer", "lightweight", "consumer"],
        [_company("金发科技", "600143", "CN", "改性塑料"), _company("Dow", "DOW", "US", "材料平台")],
        [_indicator("PP 价格", "price", "PP", 0.5), _indicator("丁二烯价格", "price", "BD", 0.5)],
    ),
    _node(
        "steel",
        "钢铁",
        "基础材料",
        "material",
        "板材、长材和特钢连接基建、汽车、风电和机械制造。",
        ["钢铁", "工程机械", "建筑建材"],
        ["ferrous", "manufacturing", "construction"],
        [_company("宝钢股份", "600019", "CN", "板材"), _company("Nucor", "NUE", "US", "电炉钢")],
        [_indicator("螺纹钢价格", "price", "REBAR", 0.45), _indicator("热卷价差", "margin", "HRC_SPREAD", 0.55)],
    ),
    _node(
        "aluminum",
        "铝材",
        "基础材料",
        "material",
        "电解铝、铝板带箔和型材受电价、地产和新能源轻量化共同驱动。",
        ["有色金属", "光伏", "新能源车"],
        ["nonferrous", "foil", "lightweight"],
        [_company("中国宏桥", "1378", "HK", "电解铝"), _company("Constellium", "CSTM", "US", "高端铝材")],
        [_indicator("沪铝价格", "price", "SHFE_AL", 0.5), _indicator("铝锭社会库存", "inventory", "AL_STOCK", 0.5)],
    ),
    _node(
        "copper",
        "铜材",
        "基础材料",
        "material",
        "铜杆、铜箔和铜连接件是电网、通信、储能和服务器的重要导体材料。",
        ["有色金属", "电力电网", "AI算力"],
        ["nonferrous", "conductive", "electrical"],
        [_company("江西铜业", "600362", "CN", "铜冶炼"), _company("Southern Copper", "SCCO", "US", "矿冶一体")],
        [_indicator("精铜加工费", "margin", "CU_PROCESS", 0.4), _indicator("铜社会库存", "inventory", "CU_STOCK", 0.6)],
    ),
    _node(
        "cement_glass",
        "水泥玻璃",
        "基础材料",
        "material",
        "水泥、玻璃和玻纤是地产、基建、光伏和家装的重要基础材料。",
        ["建筑建材", "光伏", "家居消费"],
        ["building-material", "construction", "glass"],
        [_company("海螺水泥", "600585", "CN", "水泥"), _company("福莱特", "601865", "CN", "光伏玻璃")],
        [_indicator("水泥价格指数", "price", "CEMENT", 0.45), _indicator("玻璃库存天数", "inventory", "GLASS_DAYS", 0.55)],
    ),
    _node(
        "battery_materials",
        "电池材料",
        "基础材料",
        "material",
        "正负极、电解液、隔膜和铜箔是动力电池与储能系统的关键材料层。",
        ["储能", "新能源车", "化工材料"],
        ["battery", "midstream", "high-beta"],
        [_company("容百科技", "688005", "CN", "三元正极"), _company("恩捷股份", "002812", "CN", "隔膜")],
        [_indicator("正极材料价格指数", "price", "CATHODE", 0.5), _indicator("动力电池排产", "demand", "BATTERY_SCHEDULE", 0.5)],
    ),
    _node(
        "semiconductor_materials",
        "半导体材料",
        "基础材料",
        "material",
        "硅片、靶材、特气和湿电子化学品决定晶圆制造与先进封装良率。",
        ["半导体", "电子化学品", "AI算力"],
        ["semiconductor", "wafer", "yield"],
        [_company("沪硅产业", "688126", "CN", "硅片"), _company("Shin-Etsu", role="全球硅片")],
        [_indicator("8 英寸硅片价格", "price", "WAFER_8", 0.45), _indicator("半导体材料交期", "lead-time", "SEMI_MAT_LT", 0.55)],
    ),
    _node(
        "paper_packaging",
        "包装造纸",
        "基础材料",
        "material",
        "箱板纸、生活纸和软包装连接电商履约、食品饮料和消费品牌周转。",
        ["包装造纸", "商业零售", "食品饮料"],
        ["paper", "packaging", "consumer"],
        [_company("玖龙纸业", "2689", "HK", "箱板纸"), _company("宝洁", "PG", "US", "生活纸品牌")],
        [_indicator("箱板纸价格", "price", "CONTAINERBOARD", 0.5), _indicator("快递纸箱需求指数", "demand", "PARCEL_BOX", 0.5)],
    ),
    _node(
        "biotech_feedstock",
        "生物制造原料",
        "基础材料",
        "material",
        "发酵原料、培养基、酶制剂与医药中间体连接创新药、CXO 和诊断试剂。",
        ["创新药", "CXO", "医疗器械"],
        ["biotech", "fermentation", "pharma"],
        [_company("药明生物", "2269", "HK", "生物工艺"), _company("Lonza", role="生物制造")],
        [_indicator("培养基价格指数", "price", "MEDIA_COST", 0.45), _indicator("CDMO 产能利用率", "utilization", "CDMO_UTIL", 0.55)],
    ),
    _node(
        "industrial_bearings",
        "轴承与传动",
        "通用零部件",
        "component",
        "高端轴承和传动件广泛进入风机、机器人、轨交和工程机械。",
        ["风电", "机器人", "工程机械"],
        ["component", "motion", "machinery"],
        [_company("人本股份", role="轴承"), _company("SKF", role="高端轴承")],
        [_indicator("高端轴承开工率", "utilization", "BEARING_UTIL", 0.5), _indicator("风机主轴承价格", "price", "WIND_BEARING", 0.5)],
    ),
    _node(
        "industrial_valves",
        "阀门与管件",
        "通用零部件",
        "component",
        "流程工业阀门、核级阀门和燃气管件受能源、市政与化工投资驱动。",
        ["油气", "核电", "环保水务"],
        ["component", "flow-control", "process-industry"],
        [_company("纽威股份", "603699", "CN", "工业阀门"), _company("Emerson", "EMR", "US", "流体控制")],
        [_indicator("阀门订单增速", "order", "VALVE_ORDER", 0.55), _indicator("油气资本开支", "capex", "OIL_GAS_CAPEX", 0.45)],
    ),
    _node(
        "connectors_wiring",
        "连接器与线束",
        "通用零部件",
        "component",
        "连接器、线束和高压线缆连接服务器、汽车电子、电网和家电。",
        ["通信设备", "新能源车", "消费电子"],
        ["component", "electrical", "interconnect"],
        [_company("立讯精密", "002475", "CN", "连接器"), _company("安费诺", "APH", "US", "全球连接器")],
        [_indicator("连接器订单指数", "order", "CONNECTOR_ORDER", 0.5), _indicator("高压线束渗透率", "penetration", "HV_WIRING", 0.5)],
    ),
    _node(
        "sensors",
        "传感器",
        "通用零部件",
        "component",
        "压力、温度、激光和惯性传感器是智驾、医疗、工业自动化的基础感知层。",
        ["智能驾驶", "医疗器械", "机器人"],
        ["component", "perception", "high-value"],
        [_company("歌尔微", role="MEMS"), _company("TE Connectivity", "TEL", "US", "工业与汽车传感")],
        [_indicator("车载传感器 ASP", "price", "AUTO_SENSOR_ASP", 0.45), _indicator("工业自动化景气度", "demand", "AUTO_PM", 0.55)],
    ),
    _node(
        "machine_vision",
        "机器视觉",
        "通用零部件",
        "component",
        "工业相机、光源和视觉算法支撑半导体、锂电和物流分拣。",
        ["机器人", "半导体", "物流快递"],
        ["component", "inspection", "automation"],
        [_company("奥普特", "688686", "CN", "机器视觉"), _company("Cognex", "CGNX", "US", "视觉检测")],
        [_indicator("机器视觉订单", "order", "VISION_ORDER", 0.55), _indicator("锂电设备开工率", "utilization", "BATTERY_EQUIP_UTIL", 0.45)],
    ),
    _node(
        "hydraulic_pneumatic",
        "液压气动",
        "通用零部件",
        "component",
        "液压泵阀、缸体和气动元件是工程机械、农机和自动化装备的底层件。",
        ["工程机械", "机器人", "农业机械"],
        ["component", "actuation", "equipment"],
        [_company("恒立液压", "601100", "CN", "液压件"), _company("Parker Hannifin", "PH", "US", "液压气动")],
        [_indicator("挖机开工小时数", "utilization", "EXCAVATOR_HOURS", 0.5), _indicator("液压件出口订单", "order", "HYDRAULIC_EXPORT", 0.5)],
    ),
    _node(
        "compressors",
        "压缩机与热管理",
        "通用零部件",
        "component",
        "空压机、冷机和热管理部件覆盖燃气、家电、建筑和数据中心场景。",
        ["家电", "建筑建材", "AI算力"],
        ["component", "thermal", "efficiency"],
        [_company("英维克", "002837", "CN", "热管理"), _company("Atlas Copco", "ATLKY", "US", "空压机")],
        [_indicator("商用冷机订单", "order", "CHILLER_ORDER", 0.45), _indicator("IDC 制冷需求", "demand", "IDC_COOLING", 0.55)],
    ),
    _node(
        "auto_tier1",
        "汽车零部件",
        "通用零部件",
        "component",
        "底盘、内外饰、热管理和电子电气系统连接整车、电动化与智能化升级。",
        ["汽车零部件", "新能源车", "智能驾驶"],
        ["component", "auto", "platform"],
        [_company("拓普集团", "601689", "CN", "底盘与轻量化"), _company("BorgWarner", "BWA", "US", "动力总成")],
        [_indicator("乘用车零部件库存", "inventory", "AUTO_PARTS_STOCK", 0.45), _indicator("新能源车渗透率", "penetration", "NEV_PEN", 0.55)],
    ),
    _node(
        "power_semiconductor",
        "功率器件",
        "通用零部件",
        "component",
        "IGBT、SiC 和 MOSFET 广泛进入光储、充电桩、汽车和工业驱动。",
        ["半导体", "储能", "新能源车"],
        ["component", "power-electronics", "silicon-carbide"],
        [_company("斯达半导", "603290", "CN", "IGBT"), _company("英飞凌", role="功率半导体")],
        [_indicator("SiC 模块价格", "price", "SIC_MODULE", 0.45), _indicator("车规功率器件交期", "lead-time", "POWER_SEMI_LT", 0.55)],
    ),
    _node(
        "pcb_fpc",
        "PCB 与 FPC",
        "通用零部件",
        "component",
        "印制电路板和柔性板是消费电子、服务器、通信与汽车电子的通用底座。",
        ["半导体", "消费电子", "通信设备"],
        ["component", "board", "electronics"],
        [_company("鹏鼎控股", "002938", "CN", "FPC"), _company("TTM Technologies", "TTMI", "US", "高多层板")],
        [_indicator("PCB 稼动率", "utilization", "PCB_UTIL", 0.5), _indicator("高多层板报价", "price", "HDI_PRICE", 0.5)],
    ),
    _node(
        "passive_components",
        "被动元件",
        "通用零部件",
        "component",
        "MLCC、电感、电阻和磁性元件渗透于家电、手机、汽车和服务器。",
        ["消费电子", "新能源车", "AI算力"],
        ["component", "electronics", "broad-base"],
        [_company("三环集团", "300408", "CN", "电子陶瓷"), _company("村田制作所", role="MLCC")],
        [_indicator("MLCC 价格", "price", "MLCC", 0.45), _indicator("被动元件库存周转", "inventory", "PASSIVE_INV", 0.55)],
    ),
    _node(
        "battery_cells",
        "电芯",
        "通用零部件",
        "component",
        "动力与储能电芯是电动化中枢，决定整车续航、系统成本和储能 IRR。",
        ["储能", "新能源车", "消费电子"],
        ["component", "battery-cell", "scale"],
        [_company("宁德时代", "300750", "CN", "动力与储能电芯"), _company("LG Energy Solution", role="全球电芯")],
        [_indicator("动力电池装机", "demand", "EV_BATTERY_INSTALL", 0.55), _indicator("储能电芯价格", "price", "ESS_CELL", 0.45)],
    ),
    _node(
        "integrated_circuits",
        "集成电路",
        "通用零部件",
        "component",
        "逻辑、存储、模拟和 MCU 芯片构成半导体主干，直接影响 AI、通信与终端。",
        ["半导体", "AI算力", "消费电子"],
        ["component", "chip", "compute"],
        [_company("英伟达", "NVDA", "US", "AI 芯片"), _company("中芯国际", "0981", "HK", "晶圆代工")],
        [_indicator("全球半导体销售额", "demand", "WSTS", 0.55), _indicator("HBM 合约价", "price", "HBM_PRICE", 0.45)],
    ),
    _node(
        "hbm_memory",
        "HBM 高带宽存储",
        "通用零部件",
        "component",
        "HBM 堆叠存储直接绑定 GPU 训练卡和 AI 服务器，是算力扩张中最敏感的存储瓶颈。",
        ["半导体", "AI算力", "存储芯片"],
        ["component", "memory", "ai-infra"],
        [_company("SK hynix", role="HBM 龙头"), _company("Micron", "MU", "US", "高带宽存储")],
        [_indicator("HBM 合约价", "price", "HBM_PRICE", 0.6), _indicator("HBM 供需缺口", "supply-demand", "HBM_GAP", 0.4)],
    ),
    _node(
        "ddr5_memory",
        "DDR5",
        "通用零部件",
        "component",
        "DDR5 是服务器、PC 和智能终端的通用内存底座，受 AI 服务器配比和换机周期驱动。",
        ["半导体", "AI算力", "消费电子"],
        ["component", "memory", "server"],
        [_company("三星电子", role="存储芯片"), _company("美光科技", "MU", "US", "DRAM")],
        [_indicator("DDR5 现货价", "price", "DDR5_SPOT", 0.55), _indicator("服务器 DRAM 需求", "demand", "SERVER_DRAM", 0.45)],
    ),
    _node(
        "nand_flash",
        "NAND",
        "通用零部件",
        "component",
        "NAND 闪存连接企业 SSD、手机存储和边缘设备，库存周期对价格弹性很强。",
        ["半导体", "AI算力", "消费电子"],
        ["component", "memory", "storage"],
        [_company("Kioxia", role="NAND"), _company("Western Digital", "WDC", "US", "闪存与硬盘")],
        [_indicator("NAND Flash 价格", "price", "NAND_PRICE", 0.55), _indicator("NAND 库存周转", "inventory", "NAND_INV", 0.45)],
    ),
    _node(
        "enterprise_ssd",
        "企业 SSD",
        "通用零部件",
        "component",
        "企业级 SSD 面向云厂商、数据库和 AI 数据管线，承接 NAND 与控制器景气。",
        ["AI算力", "半导体", "云计算"],
        ["component", "storage", "datacenter"],
        [_company("Solidigm", role="企业 SSD"), _company("三星电子", role="企业存储")],
        [_indicator("企业 SSD 合约价", "price", "ESSD_PRICE", 0.55), _indicator("云厂商存储资本开支", "capex", "CLOUD_STORAGE_CAPEX", 0.45)],
    ),
    _node(
        "gpu_advanced_package",
        "GPU 先进封装",
        "通用零部件",
        "component",
        "CoWoS、2.5D 和先进基板把 GPU、HBM 与高速互联整合成 AI 加速卡。",
        ["半导体", "AI算力", "封装测试"],
        ["component", "advanced-package", "gpu"],
        [_company("台积电", "TSM", "US", "先进封装"), _company("日月光", "ASX", "US", "封装测试")],
        [_indicator("CoWoS 产能", "capacity", "COWOS_CAPACITY", 0.6), _indicator("先进封装订单", "order", "ADV_PACKAGE_ORDER", 0.4)],
    ),
    _node(
        "optical_modules",
        "高速光模块",
        "通用零部件",
        "component",
        "400G、800G 与 1.6T 光模块把 AI 集群、交换机和城域传输连接起来。",
        ["通信设备", "AI算力", "云计算"],
        ["component", "optics", "datacom"],
        [_company("中际旭创", "300308", "CN", "高速光模块"), _company("Coherent", "COHR", "US", "光器件")],
        [_indicator("800G 光模块报价", "price", "800G_OPTICS", 0.55), _indicator("云厂商网络资本开支", "capex", "CLOUD_NET_CAPEX", 0.45)],
    ),
    _node(
        "mlcc",
        "MLCC",
        "通用零部件",
        "component",
        "MLCC 是服务器、汽车电子和智能终端主板的基础被动件，价格随库存周期和高容规格需求波动。",
        ["消费电子", "新能源车", "AI算力"],
        ["component", "passive", "ceramic"],
        [_company("村田制作所", role="MLCC 龙头"), _company("三环集团", "300408", "CN", "电子陶瓷")],
        [_indicator("MLCC 价格", "price", "MLCC", 0.55), _indicator("MLCC 库存周转", "inventory", "MLCC_INV", 0.45)],
    ),
    _node(
        "display_glass",
        "面板玻璃",
        "基础材料",
        "material",
        "面板玻璃基板进入显示面板、手机、PC 和车载屏，是消费电子与智能座舱的关键材料。",
        ["消费电子", "智能驾驶", "建筑建材"],
        ["material", "display", "glass"],
        [_company("康宁", "GLW", "US", "显示玻璃"), _company("东旭光电", role="玻璃基板")],
        [_indicator("面板玻璃价格", "price", "DISPLAY_GLASS", 0.55), _indicator("面板厂稼动率", "utilization", "PANEL_UTIL", 0.45)],
    ),
    _node(
        "high_speed_connectors",
        "高速连接器",
        "通用零部件",
        "component",
        "高速背板、铜缆和板端连接器服务 AI 服务器、交换机、汽车电子和消费终端。",
        ["通信设备", "AI算力", "消费电子"],
        ["component", "interconnect", "high-speed"],
        [_company("立讯精密", "002475", "CN", "精密连接"), _company("安费诺", "APH", "US", "高速连接器")],
        [_indicator("高速连接器订单", "order", "HIGHSPEED_CONN_ORDER", 0.55), _indicator("铜缆互联渗透率", "penetration", "COPPER_INTERCONNECT", 0.45)],
    ),
    _node(
        "abf_substrate",
        "ABF 载板",
        "通用零部件",
        "component",
        "ABF 载板连接晶圆、封装和服务器主板，是 GPU、CPU 与交换芯片封装的关键瓶颈。",
        ["半导体", "AI算力", "封装测试"],
        ["component", "substrate", "advanced-package"],
        [_company("欣兴电子", role="ABF 载板"), _company("Ibiden", role="高端封装基板")],
        [_indicator("ABF 载板价格", "price", "ABF_PRICE", 0.5), _indicator("ABF 产能利用率", "utilization", "ABF_UTIL", 0.5)],
    ),
    _node(
        "semiconductor_equipment",
        "半导体设备",
        "设备与系统",
        "equipment",
        "刻蚀、薄膜、清洗、检测和封装设备决定晶圆扩产节奏和国产替代空间。",
        ["半导体", "AI算力", "仪器仪表"],
        ["equipment", "capex", "国产替代"],
        [_company("北方华创", "002371", "CN", "半导体设备"), _company("ASML", "ASML", "US", "光刻设备")],
        [_indicator("晶圆厂资本开支", "capex", "FOUNDRY_CAPEX", 0.6), _indicator("设备订单交付比", "order", "SEMI_BB", 0.4)],
    ),
    _node(
        "ai_servers",
        "AI 服务器",
        "设备与系统",
        "equipment",
        "GPU 服务器、液冷、交换机和高速互联共同构成 AI 基础设施硬件。",
        ["AI算力", "通信设备", "半导体"],
        ["equipment", "server", "ai-infra"],
        [_company("浪潮信息", "000977", "CN", "服务器"), _company("Super Micro", "SMCI", "US", "AI 服务器")],
        [_indicator("AI 服务器出货量", "demand", "AI_SERVER_SHIP", 0.6), _indicator("液冷渗透率", "penetration", "LIQUID_COOLING", 0.4)],
    ),
    _node(
        "telecom_equipment",
        "通信设备",
        "设备与系统",
        "equipment",
        "光模块、交换机、基站和传输设备支撑云、AI、工业互联网和低空通信。",
        ["通信设备", "AI算力", "互联网平台"],
        ["equipment", "network", "datacom"],
        [_company("中际旭创", "300308", "CN", "光模块"), _company("思科", "CSCO", "US", "交换机")],
        [_indicator("800G 光模块报价", "price", "800G_OPTICS", 0.45), _indicator("云厂商网络资本开支", "capex", "CLOUD_NET_CAPEX", 0.55)],
    ),
    _node(
        "industrial_automation",
        "工业自动化",
        "设备与系统",
        "equipment",
        "PLC、伺服、变频器和 SCADA 是制造升级、电气化和机器换人的控制层。",
        ["机器人", "工程机械", "电力电网"],
        ["equipment", "control", "automation"],
        [_company("汇川技术", "300124", "CN", "伺服与变频"), _company("西门子", role="工业自动化")],
        [_indicator("制造业 PMI 新订单", "demand", "PMI_NEW_ORDER", 0.5), _indicator("伺服出货量", "shipment", "SERVO_SHIP", 0.5)],
    ),
    _node(
        "energy_storage_system",
        "储能系统",
        "设备与系统",
        "equipment",
        "PCS、BMS、EMS 和集成系统承接电芯，面向电网侧、工商业和户储场景。",
        ["储能", "电力电网", "新能源车"],
        ["equipment", "storage", "power-electronics"],
        [_company("阳光电源", "300274", "CN", "储能系统"), _company("Fluence", "FLNC", "US", "海外储能集成")],
        [_indicator("储能中标规模", "order", "ESS_TENDER", 0.55), _indicator("储能系统价格", "price", "ESS_SYSTEM", 0.45)],
    ),
    _node(
        "charging_swap",
        "充换电系统",
        "设备与系统",
        "equipment",
        "充电桩、换电站、运营平台和配套电力电子连接电网与电动车渗透。",
        ["新能源车", "电力电网", "储能"],
        ["equipment", "charging", "network"],
        [_company("特锐德", "300001", "CN", "充电桩"), _company("蔚来能源", role="换电网络")],
        [_indicator("公共充电桩保有量", "capacity", "PUBLIC_CHARGER", 0.5), _indicator("单桩利用率", "utilization", "CHARGER_UTIL", 0.5)],
    ),
    _node(
        "robotics_system",
        "机器人系统",
        "设备与系统",
        "equipment",
        "工业与服务机器人系统由控制、伺服、减速器和视觉共同构成。",
        ["机器人", "智能制造", "物流快递"],
        ["equipment", "robot", "mechatronics"],
        [_company("埃斯顿", "002747", "CN", "工业机器人"), _company("ABB", "ABB", "US", "机器人系统")],
        [_indicator("工业机器人产量", "shipment", "ROBOT_OUTPUT", 0.55), _indicator("汽车与锂电扩产", "capex", "AUTO_BATTERY_CAPEX", 0.45)],
    ),
    _node(
        "construction_machinery",
        "工程机械",
        "设备与系统",
        "equipment",
        "挖机、起重机和混凝土设备受基建、矿山和地产施工景气驱动。",
        ["工程机械", "建筑建材", "钢铁"],
        ["equipment", "construction", "cyclical"],
        [_company("三一重工", "600031", "CN", "工程机械"), _company("Caterpillar", "CAT", "US", "矿山与工程机械")],
        [_indicator("挖机销量", "shipment", "EXCAVATOR_SALES", 0.55), _indicator("专项债发行", "policy", "INFRA_BOND", 0.45)],
    ),
    _node(
        "rail_transit_equipment",
        "轨交装备",
        "设备与系统",
        "equipment",
        "高铁、城轨和信号系统受城市更新与公共交通投资拉动。",
        ["高铁轨交", "交通运输", "建筑建材"],
        ["equipment", "rail", "public-infra"],
        [_company("中国中车", "601766", "CN", "轨交整车"), _company("Alstom", role="轨交系统")],
        [_indicator("铁路固定资产投资", "capex", "RAIL_CAPEX", 0.55), _indicator("城轨招标规模", "order", "METRO_TENDER", 0.45)],
    ),
    _node(
        "medical_devices",
        "医疗器械",
        "设备与系统",
        "equipment",
        "影像、IVD 仪器、耗材与院内设备连接创新药、诊断和医院资本开支。",
        ["医疗器械", "创新药", "CXO"],
        ["equipment", "healthcare", "regulatory"],
        [_company("迈瑞医疗", "300760", "CN", "综合器械"), _company("GE HealthCare", "GEHC", "US", "影像")],
        [_indicator("医院设备招标额", "order", "MED_EQUIP_BID", 0.5), _indicator("IVD 设备装机", "shipment", "IVD_INSTALL", 0.5)],
    ),
    _node(
        "hvac_building_system",
        "建筑机电与 HVAC",
        "设备与系统",
        "equipment",
        "暖通、楼控、电梯和机房系统受建筑更新、商业物业和数据中心投资驱动。",
        ["建筑建材", "家电", "AI算力"],
        ["equipment", "building-system", "efficiency"],
        [_company("美的集团", "000333", "CN", "楼宇科技"), _company("Johnson Controls", "JCI", "US", "楼宇系统")],
        [_indicator("商业地产新开工", "demand", "COMM_STARTS", 0.45), _indicator("数据中心机电投资", "capex", "IDC_MEP", 0.55)],
    ),
    _node(
        "farm_equipment",
        "农业机械",
        "设备与系统",
        "equipment",
        "拖拉机、收割机和精准农业设备提高单产与规模化作业效率。",
        ["农业机械", "食品饮料", "建筑建材"],
        ["equipment", "agri", "mechanization"],
        [_company("一拖股份", "601038", "CN", "农机"), _company("Deere", "DE", "US", "全球农机")],
        [_indicator("农机补贴规模", "policy", "FARM_SUBSIDY", 0.5), _indicator("拖拉机销量", "shipment", "TRACTOR_SALES", 0.5)],
    ),
    _node(
        "smart_devices",
        "消费电子终端",
        "终端产品",
        "terminal",
        "手机、PC、可穿戴和 AR 终端承接半导体、PCB、连接器和平台流量。",
        ["消费电子", "半导体", "互联网平台"],
        ["terminal", "device", "upgrade-cycle"],
        [_company("苹果", "AAPL", "US", "生态终端"), _company("小米集团", "1810", "HK", "手机与 IoT")],
        [_indicator("全球智能手机出货量", "shipment", "SMARTPHONE_SHIP", 0.55), _indicator("PC 出货量", "shipment", "PC_SHIP", 0.45)],
    ),
    _node(
        "home_appliances",
        "家电",
        "终端产品",
        "terminal",
        "白电、小家电和智能家居受地产更新、消费升级和出口渠道共同影响。",
        ["家电", "商业零售", "消费电子"],
        ["terminal", "consumer", "export"],
        [_company("美的集团", "000333", "CN", "综合家电"), _company("惠而浦", "WHR", "US", "白电")],
        [_indicator("白电排产", "shipment", "WHITEGOODS_PLAN", 0.55), _indicator("出口订单指数", "order", "APPLIANCE_EXPORT", 0.45)],
    ),
    _node(
        "new_energy_vehicle",
        "新能源车",
        "终端产品",
        "terminal",
        "电动车整车把电池、功率器件、轻量化和智能驾驶硬件打包为最终需求。",
        ["新能源车", "汽车零部件", "储能"],
        ["terminal", "ev", "electrification"],
        [_company("比亚迪", "002594", "CN", "整车与三电"), _company("特斯拉", "TSLA", "US", "全球 EV 标杆")],
        [_indicator("新能源车渗透率", "penetration", "NEV_SHARE", 0.6), _indicator("月度批发销量", "shipment", "NEV_WHOLESALE", 0.4)],
    ),
    _node(
        "intelligent_vehicle",
        "智能驾驶整车",
        "终端产品",
        "terminal",
        "高阶辅助驾驶把芯片、传感器、域控和软件服务整合到整车场景。",
        ["智能驾驶", "新能源车", "软件服务"],
        ["terminal", "ad", "software-defined"],
        [_company("小鹏汽车", "XPEV", "US", "智驾车型"), _company("Mobileye", "MBLY", "US", "智驾方案")],
        [_indicator("L2+ 渗透率", "penetration", "ADAS_PEN", 0.55), _indicator("高阶智驾车型销量", "shipment", "ADAS_SALES", 0.45)],
    ),
    _node(
        "industrial_robot",
        "工业机器人应用",
        "终端产品",
        "terminal",
        "机器人在汽车、锂电、3C 和仓储产线落地，映射制造业资本开支方向。",
        ["机器人", "工程机械", "物流快递"],
        ["terminal", "factory", "automation"],
        [_company("新松机器人", "300024", "CN", "工业机器人"), _company("Fanuc", role="工业机器人")],
        [_indicator("制造业机器人密度", "penetration", "ROBOT_DENSITY", 0.45), _indicator("汽车工厂扩产", "capex", "AUTO_FACTORY_CAPEX", 0.55)],
    ),
    _node(
        "low_altitude_aircraft",
        "低空飞行器",
        "终端产品",
        "terminal",
        "无人机与 eVTOL 把电池、复材、通信和导航带到低空物流与巡检场景。",
        ["低空经济", "新能源车", "通信设备"],
        ["terminal", "air-mobility", "emerging"],
        [_company("大疆创新", role="无人机"), _company("亿航智能", "EH", "US", "eVTOL")],
        [_indicator("无人机出货量", "shipment", "DRONE_SHIP", 0.55), _indicator("低空空域开放进度", "policy", "LOW_ALTITUDE_POLICY", 0.45)],
    ),
    _node(
        "building_construction",
        "建筑与城市更新",
        "终端产品",
        "terminal",
        "基建、保障房、城市更新和工业厂房共同承接钢铁、水泥、机电与金融需求。",
        ["建筑建材", "房地产", "工程机械"],
        ["terminal", "construction", "urban"],
        [_company("中国建筑", "601668", "CN", "总承包"), _company("Vinci", role="全球工程承包")],
        [_indicator("基建投资增速", "demand", "INFRA_GROWTH", 0.55), _indicator("新开工面积", "demand", "STARTS_AREA", 0.45)],
    ),
    _node(
        "innovative_drugs",
        "创新药",
        "终端产品",
        "terminal",
        "创新药把生物制造、CXO、临床资源和支付体系转化为商业化药品。",
        ["创新药", "CXO", "医疗器械"],
        ["terminal", "pharma", "pipeline"],
        [_company("恒瑞医药", "600276", "CN", "创新药"), _company("礼来", "LLY", "US", "全球创新药")],
        [_indicator("IND 申报数量", "pipeline", "IND_FILINGS", 0.45), _indicator("医保谈判放量", "policy", "NRDL_UPTAKE", 0.55)],
    ),
    _node(
        "diagnostics_ivd",
        "诊断与 IVD",
        "终端产品",
        "terminal",
        "体外诊断试剂和检测服务连接医院、基层医疗和消费健康场景。",
        ["医疗器械", "CXO", "商业零售"],
        ["terminal", "diagnostics", "healthcare"],
        [_company("圣湘生物", "688289", "CN", "分子诊断"), _company("罗氏诊断", role="IVD 平台")],
        [_indicator("检验人次", "demand", "LAB_TESTS", 0.55), _indicator("试剂集采降幅", "policy", "IVD_PROCUREMENT", 0.45)],
    ),
    _node(
        "branded_food_beverage",
        "食品饮料",
        "终端产品",
        "terminal",
        "白酒、乳制品、休闲食品和饮料面向大众消费与餐饮场景。",
        ["食品饮料", "白酒", "商业零售"],
        ["terminal", "consumer", "brand"],
        [_company("贵州茅台", "600519", "CN", "白酒"), _company("可口可乐", "KO", "US", "饮料品牌")],
        [_indicator("社零餐饮收入", "demand", "CATERING_RETAIL", 0.5), _indicator("渠道库存月数", "inventory", "FNB_CHANNEL_INV", 0.5)],
    ),
    _node(
        "apparel_home",
        "纺织服饰与家居",
        "终端产品",
        "terminal",
        "服装、家纺和家居用品受外需、电商流量和地产后周期共同影响。",
        ["纺织服饰", "家居消费", "商业零售"],
        ["terminal", "consumer", "export"],
        [_company("申洲国际", "2313", "HK", "服装制造"), _company("Nike", "NKE", "US", "品牌渠道")],
        [_indicator("服装零售额", "demand", "APPAREL_RETAIL", 0.5), _indicator("家居出口订单", "order", "HOME_EXPORT", 0.5)],
    ),
    _node(
        "distributed_energy",
        "分布式能源",
        "终端产品",
        "terminal",
        "户用与工商业光储充微网把电力系统直接嵌入园区、建筑和终端负荷。",
        ["光伏", "储能", "电力电网"],
        ["terminal", "microgrid", "onsite-power"],
        [_company("Enphase", "ENPH", "US", "户用逆变器"), _company("固德威", "688390", "CN", "分布式逆变器")],
        [_indicator("户储装机", "shipment", "HOME_STORAGE", 0.45), _indicator("工商业分布式新增", "demand", "CNI_DG", 0.55)],
    ),
    _node(
        "ecommerce_retail",
        "商业零售与电商",
        "渠道与服务",
        "service",
        "线下零售、电商平台和品牌渠道承接消费电子、食品饮料和家居家电销售。",
        ["商业零售", "互联网平台", "消费电子"],
        ["service", "channel", "traffic"],
        [_company("京东", "JD", "US", "自营零售"), _company("沃尔玛", "WMT", "US", "全球零售")],
        [_indicator("网上零售额", "gmv", "ONLINE_RETAIL", 0.55), _indicator("社零总额", "sales", "RETAIL_SALES", 0.45)],
    ),
    _node(
        "internet_platform",
        "互联网平台",
        "渠道与服务",
        "service",
        "搜索、社交、内容与本地生活平台连接流量分发、广告和交易闭环。",
        ["互联网平台", "游戏传媒", "商业零售"],
        ["service", "platform", "traffic"],
        [_company("腾讯控股", "0700", "HK", "社交平台"), _company("Meta", "META", "US", "全球广告平台")],
        [_indicator("在线广告收入", "revenue", "DIGITAL_ADS", 0.5), _indicator("用户时长增速", "traffic", "TIME_SPENT", 0.5)],
    ),
    _node(
        "software_cloud",
        "软件服务与云",
        "渠道与服务",
        "service",
        "企业软件、SaaS、云资源和行业数字化服务承接 AI 基础设施的商业化。",
        ["软件服务", "AI算力", "银行"],
        ["service", "cloud", "subscription"],
        [_company("金山办公", "688111", "CN", "办公软件"), _company("微软", "MSFT", "US", "云与企业软件")],
        [_indicator("公有云支出增速", "demand", "CLOUD_SPEND", 0.55), _indicator("SaaS 续费率", "retention", "SAAS_RENEWAL", 0.45)],
    ),
    _node(
        "ai_compute",
        "AI 算力服务",
        "渠道与服务",
        "service",
        "算力租赁、训练推理平台和数据中心运维把芯片与服务器转为可售服务。",
        ["AI算力", "软件服务", "互联网平台"],
        ["service", "compute", "data-center"],
        [_company("Amazon Web Services", role="云算力"), _company("阿里云", role="国内云算力")],
        [_indicator("GPU 租赁价格", "price", "GPU_RENT", 0.45), _indicator("机柜上架率", "utilization", "IDC_RACK_UTIL", 0.55)],
    ),
    _node(
        "banking",
        "银行",
        "渠道与服务",
        "service",
        "银行提供信贷、结算和产业资本周转，是地产、基建和消费金融的核心枢纽。",
        ["银行", "房地产", "商业零售"],
        ["service", "finance", "credit"],
        [_company("招商银行", "600036", "CN", "零售银行"), _company("JPMorgan Chase", "JPM", "US", "综合银行")],
        [_indicator("社融增速", "credit", "TSF_GROWTH", 0.55), _indicator("制造业中长期贷款", "credit", "MANU_LOAN", 0.45)],
    ),
    _node(
        "insurance",
        "保险",
        "渠道与服务",
        "service",
        "寿险、财险和健康险覆盖车辆、医疗、物流与居民财富配置场景。",
        ["保险", "新能源车", "医疗器械"],
        ["service", "risk-transfer", "asset-allocation"],
        [_company("中国平安", "601318", "CN", "综合保险"), _company("UnitedHealth", "UNH", "US", "健康险与医疗")],
        [_indicator("保费收入增速", "premium", "PREMIUM_GROWTH", 0.5), _indicator("长端利率", "macro", "LONG_BOND", 0.5)],
    ),
    _node(
        "brokerage_asset_mgmt",
        "券商与资管",
        "渠道与服务",
        "service",
        "券商、财富管理和一级二级资本市场服务连接科技成长与产业融资。",
        ["券商", "银行", "互联网平台"],
        ["service", "capital-market", "wealth"],
        [_company("中信证券", "600030", "CN", "综合券商"), _company("高盛", "GS", "US", "投行与资管")],
        [_indicator("两市成交额", "trading", "MARKET_TURNOVER", 0.55), _indicator("IPO 融资额", "financing", "IPO_PROCEEDS", 0.45)],
    ),
    _node(
        "logistics_express",
        "物流快递",
        "渠道与服务",
        "service",
        "快递、仓配、冷链和同城履约连接电商、制造业和食品医药流通。",
        ["物流快递", "商业零售", "食品饮料"],
        ["service", "fulfillment", "network"],
        [_company("顺丰控股", "002352", "CN", "综合物流"), _company("UPS", "UPS", "US", "全球物流")],
        [_indicator("快递业务量", "volume", "EXPRESS_VOLUME", 0.55), _indicator("单票收入", "price", "PARCEL_YIELD", 0.45)],
    ),
    _node(
        "shipping_ports",
        "航运港口",
        "渠道与服务",
        "service",
        "集运、油运、散运和港口吞吐承接全球能源、矿产和消费品跨境流动。",
        ["航运港口", "物流快递", "油气"],
        ["service", "shipping", "trade"],
        [_company("中远海控", "601919", "CN", "集运"), _company("马士基", role="全球航运")],
        [_indicator("SCFI 运价", "price", "SCFI", 0.45), _indicator("港口集装箱吞吐量", "volume", "PORT_TEU", 0.55)],
    ),
    _node(
        "healthcare_services",
        "医疗服务",
        "渠道与服务",
        "service",
        "医院、诊疗中心和互联网医疗承接器械、药品和支付体系需求。",
        ["医疗器械", "创新药", "保险"],
        ["service", "hospital", "healthcare"],
        [_company("爱尔眼科", "300015", "CN", "专科医疗"), _company("HCA Healthcare", "HCA", "US", "医院集团")],
        [_indicator("门急诊人次", "volume", "OUTPATIENT", 0.5), _indicator("医疗服务收入", "revenue", "HEALTHCARE_REV", 0.5)],
    ),
    _node(
        "travel_hospitality",
        "旅游酒店",
        "渠道与服务",
        "service",
        "酒店、景区、航空出行和本地休闲消费把交通、餐饮和支付串成服务闭环。",
        ["旅游酒店", "交通运输", "食品饮料"],
        ["service", "travel", "offline-consumption"],
        [_company("携程集团", "TCOM", "US", "在线旅游"), _company("万豪国际", "MAR", "US", "酒店")],
        [_indicator("国内航班执行率", "mobility", "FLIGHT_UTIL", 0.45), _indicator("酒店 ADR", "price", "HOTEL_ADR", 0.55)],
    ),
    _node(
        "payments_fintech",
        "支付与金融科技",
        "渠道与服务",
        "service",
        "支付、消费金融和金融科技基础设施打通零售、出行和平台交易结算。",
        ["软件服务", "银行", "互联网平台"],
        ["service", "payments", "fintech"],
        [_company("PayPal", "PYPL", "US", "全球支付"), _company("拉卡拉", "300773", "CN", "支付服务")],
        [_indicator("第三方支付流水", "gmv", "TPV", 0.55), _indicator("消费贷余额", "credit", "CONSUMER_LOAN", 0.45)],
    ),
    _node(
        "scrap_steel_recycling",
        "废钢循环",
        "回收与再生产",
        "recycle",
        "废钢回收与电炉冶炼提高钢铁链循环比例，降低能耗与碳强度。",
        ["钢铁", "建筑建材", "环保水务"],
        ["recycle", "ferrous", "circular"],
        [_company("华宏科技", "002645", "CN", "再生资源设备"), _company("Commercial Metals", "CMC", "US", "电炉钢")],
        [_indicator("废钢价格", "price", "SCRAP_STEEL", 0.5), _indicator("电炉钢占比", "penetration", "EAF_SHARE", 0.5)],
    ),
    _node(
        "battery_recycling",
        "电池回收",
        "回收与再生产",
        "recycle",
        "退役动力电池回收和梯次利用回流镍钴锂与磷资源，降低材料波动。",
        ["储能", "新能源车", "有色金属"],
        ["recycle", "battery", "materials"],
        [_company("格林美", "002340", "CN", "动力电池回收"), _company("Li-Cycle", "LICY", "US", "海外回收")],
        [_indicator("退役电池规模", "supply", "RETIRED_BATTERY", 0.55), _indicator("黑粉折扣率", "margin", "BLACK_MASS", 0.45)],
    ),
    _node(
        "electronics_recycling",
        "电子废弃物回收",
        "回收与再生产",
        "recycle",
        "废旧手机、家电和服务器拆解回收铜、金、塑料和部分元器件。",
        ["消费电子", "家电", "半导体"],
        ["recycle", "electronics", "urban-mine"],
        [_company("中再资环", "600217", "CN", "家电拆解"), _company("Sims", "SGM", "AU", "电子回收")],
        [_indicator("四机一脑回收量", "volume", "EWASTE_VOLUME", 0.55), _indicator("再生铜价格折价", "price", "RECYCLE_CU_DISC", 0.45)],
    ),
    _node(
        "plastics_recycling",
        "塑料再生",
        "回收与再生产",
        "recycle",
        "再生塑料和化学回收把包装、家电和汽车链条带入低碳循环。",
        ["化工材料", "包装造纸", "家电"],
        ["recycle", "polymer", "low-carbon"],
        [_company("英科再生", "688087", "CN", "再生塑料"), _company("Waste Management", "WM", "US", "固废资源化")],
        [_indicator("再生 PET 价格", "price", "RPET", 0.5), _indicator("再生塑料掺混比例", "penetration", "PCR_RATE", 0.5)],
    ),
    _node(
        "used_car_circulation",
        "二手车流通",
        "回收与再生产",
        "recycle",
        "二手车和残值管理延长汽车资产生命周期，并决定车险与金融附加价值。",
        ["新能源车", "汽车零部件", "保险"],
        ["recycle", "resale", "asset-turnover"],
        [_company("汽车之家", "ATHM", "US", "车交易流量"), _company("Carvana", "CVNA", "US", "二手车零售")],
        [_indicator("二手车交易量", "volume", "USED_CAR_VOLUME", 0.55), _indicator("新能源车残值率", "price", "NEV_RESIDUAL", 0.45)],
    ),
    _node(
        "renewable_fuel_bioenergy",
        "生物质与再生燃料",
        "回收与再生产",
        "recycle",
        "餐厨废弃物、秸秆和废油脂再生产生物燃料、电力和工业蒸汽。",
        ["环保水务", "食品饮料", "电力电网"],
        ["recycle", "bioenergy", "fuel"],
        [_company("光大环境", "0257", "HK", "垃圾发电"), _company("Neste", "NTOIY", "US", "可再生燃料")],
        [_indicator("垃圾焚烧发电量", "generation", "WTE_POWER", 0.45), _indicator("UCO 价格", "price", "UCO_PRICE", 0.55)],
    ),
]


CHAIN_EDGES = [
    _edge("coal", "thermal_power", "supplies", "火电燃料", 0.98),
    _edge("coal", "petrochemicals", "supplies", "煤化工原料", 0.46),
    _edge("crude_oil", "refinery_fuels", "supplies", "原油炼化", 0.98),
    _edge("crude_oil", "petrochemicals", "supplies", "石脑油与芳烃原料", 0.84),
    _edge("natural_gas", "lng_gas", "supplies", "气源与 LNG 贸易", 0.92),
    _edge("natural_gas", "thermal_power", "supplies", "燃气发电燃料", 0.72),
    _edge("natural_gas", "petrochemicals", "supplies", "甲醇与氨化工原料", 0.55),
    _edge("iron_ore", "steel", "smelts_into", "炼钢原料", 0.96),
    _edge("copper_ore", "copper", "smelts_into", "精炼铜原料", 0.95),
    _edge("bauxite", "aluminum", "smelts_into", "氧化铝与电解铝原料", 0.94),
    _edge("lithium_ore", "battery_materials", "supplies", "锂盐原料", 0.96),
    _edge("nickel_ore", "battery_materials", "supplies", "三元前驱体原料", 0.78),
    _edge("rare_earth_ore", "robotics_system", "supplies", "永磁材料", 0.56),
    _edge("rare_earth_ore", "new_energy_vehicle", "supplies", "驱动电机磁材", 0.58),
    _edge("potash_phosphate", "corn_soybean", "fertilizes", "作物养分投入", 0.82),
    _edge("corn_soybean", "branded_food_beverage", "feeds", "粮油与淀粉糖原料", 0.76),
    _edge("timber_pulp", "paper_packaging", "supplies", "纸浆与原纸", 0.93),
    _edge("power_grid", "ai_compute", "powers", "数据中心与算力负荷", 0.95),
    _edge("power_grid", "charging_swap", "powers", "充换电接入", 0.88),
    _edge("power_grid", "energy_storage_system", "connects", "并网与调峰", 0.9),
    _edge("power_grid", "distributed_energy", "connects", "分布式并网", 0.82),
    _edge("thermal_power", "power_grid", "feeds", "火电上网电量", 0.92),
    _edge("nuclear_power", "power_grid", "feeds", "核电基荷", 0.76),
    _edge("hydropower", "power_grid", "feeds", "清洁基荷", 0.74),
    _edge("solar_power", "power_grid", "feeds", "光伏上网电量", 0.78),
    _edge("wind_power", "power_grid", "feeds", "风电上网电量", 0.78),
    _edge("lng_gas", "thermal_power", "feeds", "燃气机组燃料", 0.66),
    _edge("refinery_fuels", "shipping_ports", "supplies", "船燃与油运", 0.58),
    _edge("water_utility", "semiconductor_materials", "supports", "超纯水与废水处理", 0.63),
    _edge("petrochemicals", "specialty_chemicals", "feeds", "中间体平台", 0.87),
    _edge("petrochemicals", "plastics_rubber", "feeds", "聚烯烃与弹性体", 0.9),
    _edge("specialty_chemicals", "battery_materials", "feeds", "电解液与添加剂", 0.79),
    _edge("specialty_chemicals", "semiconductor_materials", "feeds", "特气与湿电子化学品", 0.82),
    _edge("plastics_rubber", "auto_tier1", "supplies", "内外饰与轻量化材料", 0.75),
    _edge("plastics_rubber", "home_appliances", "supplies", "外壳与绝缘件", 0.68),
    _edge("steel", "construction_machinery", "supplies", "结构件与板材", 0.72),
    _edge("steel", "rail_transit_equipment", "supplies", "车体与轨道钢材", 0.66),
    _edge("steel", "building_construction", "supplies", "螺纹钢与型材", 0.88),
    _edge("steel", "wind_power", "supplies", "塔筒与铸锻件", 0.55),
    _edge("aluminum", "new_energy_vehicle", "supplies", "轻量化车身", 0.58),
    _edge("aluminum", "smart_devices", "supplies", "机壳与结构件", 0.51),
    _edge("aluminum", "solar_power", "supplies", "边框与支架", 0.57),
    _edge("copper", "power_grid", "supplies", "电缆与变压器导体", 0.82),
    _edge("copper", "connectors_wiring", "supplies", "铜材与线缆", 0.8),
    _edge("copper", "telecom_equipment", "supplies", "高速连接与散热铜材", 0.52),
    _edge("copper", "ai_servers", "supplies", "铜缆与散热部件", 0.54),
    _edge("cement_glass", "building_construction", "supplies", "主体建材", 0.93),
    _edge("cement_glass", "solar_power", "supplies", "光伏玻璃", 0.57),
    _edge("battery_materials", "battery_cells", "supplies", "正负极隔膜电解液", 0.96),
    _edge("semiconductor_materials", "integrated_circuits", "supplies", "硅片与特气", 0.93),
    _edge("semiconductor_materials", "semiconductor_equipment", "supports", "验证耗材与关键材料", 0.36),
    _edge("semiconductor_materials", "power_semiconductor", "supplies", "功率芯片晶圆与外延材料", 0.7),
    _edge("semiconductor_materials", "hbm_memory", "supplies", "硅片、特气与光刻材料", 0.78),
    _edge("semiconductor_materials", "ddr5_memory", "supplies", "DRAM 晶圆材料", 0.72),
    _edge("semiconductor_materials", "nand_flash", "supplies", "3D NAND 材料", 0.7),
    _edge("semiconductor_materials", "abf_substrate", "supplies", "树脂、铜箔与基板材料", 0.61),
    _edge("paper_packaging", "ecommerce_retail", "supplies", "快递包装", 0.63),
    _edge("paper_packaging", "branded_food_beverage", "supplies", "食品饮料包装", 0.66),
    _edge("biotech_feedstock", "innovative_drugs", "feeds", "生物原液与中间体", 0.73),
    _edge("biotech_feedstock", "diagnostics_ivd", "feeds", "酶制剂与抗原抗体", 0.62),
    _edge("industrial_bearings", "wind_power", "enables", "主轴承与偏航系统", 0.58),
    _edge("industrial_bearings", "construction_machinery", "enables", "回转支承与传动", 0.61),
    _edge("industrial_bearings", "robotics_system", "enables", "关节传动", 0.49),
    _edge("industrial_valves", "lng_gas", "enables", "燃气管网与接收站", 0.53),
    _edge("industrial_valves", "refinery_fuels", "enables", "炼化流程控制", 0.58),
    _edge("industrial_valves", "water_utility", "enables", "市政与工业水务", 0.55),
    _edge("connectors_wiring", "ai_servers", "enables", "高速互连", 0.62),
    _edge("connectors_wiring", "telecom_equipment", "enables", "通信互连", 0.66),
    _edge("connectors_wiring", "new_energy_vehicle", "enables", "高压线束", 0.69),
    _edge("connectors_wiring", "smart_devices", "enables", "精密连接", 0.5),
    _edge("sensors", "industrial_automation", "enables", "过程控制感知", 0.56),
    _edge("sensors", "medical_devices", "enables", "监护与诊断感知", 0.49),
    _edge("sensors", "intelligent_vehicle", "enables", "车载感知", 0.78),
    _edge("sensors", "low_altitude_aircraft", "enables", "导航与姿态感知", 0.57),
    _edge("machine_vision", "industrial_automation", "enables", "质检与引导", 0.62),
    _edge("machine_vision", "industrial_robot", "enables", "分拣与上下料", 0.56),
    _edge("hydraulic_pneumatic", "construction_machinery", "enables", "执行系统", 0.84),
    _edge("hydraulic_pneumatic", "farm_equipment", "enables", "农机作业系统", 0.54),
    _edge("compressors", "hvac_building_system", "enables", "制冷与空调", 0.71),
    _edge("auto_tier1", "new_energy_vehicle", "supplies", "底盘热管理与内外饰", 0.87),
    _edge("auto_tier1", "intelligent_vehicle", "supplies", "域控与执行机构", 0.76),
    _edge("power_semiconductor", "energy_storage_system", "supplies", "PCS 功率模块", 0.73),
    _edge("power_semiconductor", "charging_swap", "supplies", "充电模块", 0.68),
    _edge("power_semiconductor", "new_energy_vehicle", "supplies", "电驱与 OBC", 0.74),
    _edge("power_semiconductor", "industrial_automation", "supplies", "变频与伺服驱动", 0.55),
    _edge("power_semiconductor", "solar_power", "supplies", "逆变器核心器件", 0.56),
    _edge("cement_glass", "display_glass", "supplies", "高洁净玻璃基板", 0.52),
    _edge("pcb_fpc", "smart_devices", "supplies", "主板与柔性板", 0.82),
    _edge("pcb_fpc", "medical_devices", "supplies", "仪器电路板", 0.46),
    _edge("pcb_fpc", "telecom_equipment", "supplies", "高多层与高速板", 0.68),
    _edge("pcb_fpc", "intelligent_vehicle", "supplies", "车载控制板", 0.63),
    _edge("pcb_fpc", "gpu_advanced_package", "supports", "封装与加速卡载板", 0.55),
    _edge("pcb_fpc", "ai_servers", "supplies", "服务器主板与背板", 0.67),
    _edge("pcb_fpc", "optical_modules", "supports", "光模块 PCB 与封装板", 0.58),
    _edge("passive_components", "ai_servers", "supplies", "电源与滤波", 0.53),
    _edge("passive_components", "telecom_equipment", "supplies", "通信板卡元件", 0.58),
    _edge("passive_components", "smart_devices", "supplies", "主板被动件", 0.63),
    _edge("mlcc", "ai_servers", "supplies", "高容电源去耦", 0.6),
    _edge("mlcc", "telecom_equipment", "supplies", "通信板卡被动件", 0.57),
    _edge("mlcc", "smart_devices", "supplies", "终端主板被动件", 0.66),
    _edge("mlcc", "new_energy_vehicle", "supplies", "车规高可靠电容", 0.62),
    _edge("display_glass", "smart_devices", "supplies", "手机、PC 与可穿戴显示", 0.68),
    _edge("display_glass", "intelligent_vehicle", "supplies", "车载显示与座舱屏", 0.42),
    _edge("battery_cells", "energy_storage_system", "supplies", "储能电芯", 0.85),
    _edge("battery_cells", "new_energy_vehicle", "supplies", "动力电池", 0.93),
    _edge("battery_cells", "distributed_energy", "supplies", "户储与工商储电芯", 0.66),
    _edge("copper", "high_speed_connectors", "supplies", "高速铜材与端子", 0.63),
    _edge("connectors_wiring", "high_speed_connectors", "specializes_into", "高速背板与铜缆互联", 0.62),
    _edge("high_speed_connectors", "ai_servers", "enables", "背板、铜缆与板端连接", 0.68),
    _edge("high_speed_connectors", "telecom_equipment", "enables", "交换机与光电互联", 0.63),
    _edge("high_speed_connectors", "smart_devices", "enables", "精密高速连接", 0.46),
    _edge("integrated_circuits", "ai_servers", "supplies", "GPU 与 CPU", 0.9),
    _edge("integrated_circuits", "telecom_equipment", "supplies", "交换芯片与 DSP", 0.72),
    _edge("integrated_circuits", "smart_devices", "supplies", "SoC 与存储", 0.85),
    _edge("integrated_circuits", "intelligent_vehicle", "supplies", "智驾芯片与 MCU", 0.79),
    _edge("integrated_circuits", "power_semiconductor", "branches_into", "功率半导体器件", 0.62),
    _edge("integrated_circuits", "hbm_memory", "branches_into", "高带宽存储器件", 0.76),
    _edge("integrated_circuits", "ddr5_memory", "branches_into", "服务器与终端内存", 0.72),
    _edge("integrated_circuits", "nand_flash", "branches_into", "闪存器件", 0.68),
    _edge("integrated_circuits", "gpu_advanced_package", "packages_into", "GPU 与加速卡封装", 0.82),
    _edge("semiconductor_equipment", "integrated_circuits", "manufactures", "晶圆制造设备", 0.88),
    _edge("semiconductor_equipment", "hbm_memory", "manufactures", "DRAM 与 TSV 工艺设备", 0.72),
    _edge("semiconductor_equipment", "gpu_advanced_package", "manufactures", "先进封装设备", 0.64),
    _edge("hbm_memory", "gpu_advanced_package", "integrates_with", "HBM 堆叠封装", 0.88),
    _edge("hbm_memory", "ai_servers", "supplies", "训练卡高带宽内存", 0.87),
    _edge("ddr5_memory", "ai_servers", "supplies", "服务器系统内存", 0.66),
    _edge("ddr5_memory", "smart_devices", "supplies", "终端内存", 0.42),
    _edge("nand_flash", "enterprise_ssd", "integrates_into", "企业级固态硬盘", 0.88),
    _edge("nand_flash", "smart_devices", "supplies", "终端存储", 0.57),
    _edge("enterprise_ssd", "ai_servers", "supplies", "本地训练数据存储", 0.7),
    _edge("enterprise_ssd", "ai_compute", "enables", "数据集与向量存储", 0.55),
    _edge("abf_substrate", "gpu_advanced_package", "supports", "高端封装基板", 0.86),
    _edge("gpu_advanced_package", "ai_servers", "supplies", "GPU 加速卡", 0.9),
    _edge("integrated_circuits", "optical_modules", "supplies", "DSP、Driver 与 CPO 芯片", 0.58),
    _edge("high_speed_connectors", "optical_modules", "connects", "光电接口与高速连接", 0.43),
    _edge("optical_modules", "telecom_equipment", "supplies", "交换机与传输光模块", 0.83),
    _edge("optical_modules", "ai_servers", "connects", "集群高速互联", 0.72),
    _edge("optical_modules", "ai_compute", "enables", "算力网络互联", 0.76),
    _edge("ai_servers", "ai_compute", "hosts", "训练推理集群", 0.95),
    _edge("telecom_equipment", "internet_platform", "connects", "内容分发与接入", 0.68),
    _edge("telecom_equipment", "ai_compute", "connects", "算力网络与交换", 0.74),
    _edge("industrial_automation", "industrial_robot", "controls", "产线自动化", 0.76),
    _edge("industrial_automation", "battery_cells", "controls", "电芯制造线", 0.47),
    _edge("energy_storage_system", "power_grid", "stabilizes", "调峰调频与备用", 0.8),
    _edge("energy_storage_system", "distributed_energy", "enables", "光储充一体化", 0.66),
    _edge("charging_swap", "new_energy_vehicle", "serves", "补能网络", 0.83),
    _edge("robotics_system", "industrial_robot", "delivers", "整机与系统集成", 0.89),
    _edge("construction_machinery", "building_construction", "builds", "施工装备", 0.86),
    _edge("medical_devices", "healthcare_services", "serves", "院内设备与耗材", 0.92),
    _edge("medical_devices", "diagnostics_ivd", "supports", "IVD 仪器平台", 0.57),
    _edge("hvac_building_system", "building_construction", "installs_into", "楼宇机电系统", 0.82),
    _edge("hvac_building_system", "ai_compute", "cools", "数据中心散热", 0.56),
    _edge("farm_equipment", "corn_soybean", "supports", "规模化作业", 0.42),
    _edge("smart_devices", "internet_platform", "connects_to", "流量入口", 0.82),
    _edge("smart_devices", "ecommerce_retail", "sold_via", "终端销售渠道", 0.51),
    _edge("home_appliances", "ecommerce_retail", "sold_via", "线上线下销售", 0.67),
    _edge("new_energy_vehicle", "used_car_circulation", "reenters", "残值与二手流通", 0.47),
    _edge("intelligent_vehicle", "software_cloud", "subscribes_to", "座舱与智驾订阅", 0.38),
    _edge("low_altitude_aircraft", "logistics_express", "serves", "无人机配送与巡检", 0.41),
    _edge("building_construction", "banking", "financed_by", "项目贷款与按揭", 0.59),
    _edge("building_construction", "scrap_steel_recycling", "produces", "拆改废钢", 0.17),
    _edge("innovative_drugs", "healthcare_services", "prescribed_in", "医院与专科渠道", 0.75),
    _edge("innovative_drugs", "insurance", "reimbursed_by", "医保与商保支付", 0.42),
    _edge("diagnostics_ivd", "healthcare_services", "used_in", "检验检测服务", 0.84),
    _edge("branded_food_beverage", "ecommerce_retail", "sold_via", "零售与即时配送", 0.64),
    _edge("branded_food_beverage", "renewable_fuel_bioenergy", "produces", "餐厨与有机废弃物", 0.21),
    _edge("apparel_home", "ecommerce_retail", "sold_via", "线上品牌渠道", 0.68),
    _edge("distributed_energy", "power_grid", "balances", "虚拟电厂与就地消纳", 0.43),
    _edge("ecommerce_retail", "logistics_express", "outsources", "仓配履约", 0.88),
    _edge("ecommerce_retail", "payments_fintech", "settles_with", "支付结算", 0.73),
    _edge("internet_platform", "software_cloud", "uses", "广告与推荐系统云化", 0.44),
    _edge("internet_platform", "ai_compute", "consumes", "模型训练与推理", 0.61),
    _edge("internet_platform", "payments_fintech", "embeds", "支付闭环", 0.54),
    _edge("internet_platform", "ecommerce_retail", "converts_to", "流量转交易", 0.48),
    _edge("software_cloud", "ai_compute", "orchestrates", "模型平台与调度", 0.68),
    _edge("software_cloud", "banking", "serves", "金融 IT", 0.44),
    _edge("banking", "new_energy_vehicle", "finances", "汽车消费金融", 0.28),
    _edge("insurance", "healthcare_services", "pays_for", "健康险与医疗赔付", 0.4),
    _edge("shipping_ports", "logistics_express", "feeds", "海运与港口分拨", 0.66),
    _edge("payments_fintech", "ecommerce_retail", "serves", "交易支付", 0.71),
    _edge("scrap_steel_recycling", "steel", "feeds_back", "废钢回炉", 0.82),
    _edge("battery_recycling", "battery_materials", "feeds_back", "镍钴锂再生", 0.84),
    _edge("electronics_recycling", "copper", "feeds_back", "再生铜回收", 0.43),
    _edge("plastics_rubber", "plastics_recycling", "produces", "废塑料回收来源", 0.27),
    _edge("plastics_recycling", "plastics_rubber", "feeds_back", "再生树脂", 0.68),
    _edge("renewable_fuel_bioenergy", "power_grid", "feeds", "垃圾焚烧与生物质发电", 0.36),
    _edge("smart_devices", "electronics_recycling", "produces", "手机与 PC 回收", 0.24),
    _edge("home_appliances", "electronics_recycling", "produces", "家电拆解", 0.25),
    _edge("new_energy_vehicle", "battery_recycling", "produces", "退役动力电池", 0.32),
    _edge("battery_cells", "battery_recycling", "routes_to", "制造 scrap 与退役电芯", 0.18),
]


WORLD_REGIONS = [
    _region(
        "north_america",
        "北美",
        22,
        28,
        "技术平台与高端消费中心",
        "AI 芯片、云算力、创新药、消费电子品牌和油气页岩供给。",
        [
            "crude_oil",
            "natural_gas",
            "integrated_circuits",
            "hbm_memory",
            "ddr5_memory",
            "nand_flash",
            "enterprise_ssd",
            "gpu_advanced_package",
            "ai_servers",
            "ai_compute",
            "software_cloud",
            "innovative_drugs",
            "ecommerce_retail",
        ],
        ["NASDAQ", "NYSE", "Houston", "Silicon Valley"],
    ),
    _region(
        "latin_america",
        "拉美",
        24,
        60,
        "资源出口与农产品供给区",
        "铜、锂、纸浆、粮食和油脂，是全球材料与食品链的重要资源腹地。",
        ["copper_ore", "lithium_ore", "corn_soybean", "timber_pulp", "shipping_ports"],
        ["B3", "Santiago", "Lima"],
    ),
    _region(
        "europe",
        "欧洲",
        48,
        24,
        "高端制造与绿色转型区域",
        "工业自动化、轨交、风电、医疗和金融服务成熟，碳政策外溢明显。",
        ["wind_power", "industrial_automation", "rail_transit_equipment", "medical_devices", "insurance", "travel_hospitality"],
        ["Euronext", "LSE", "Frankfurt", "Paris"],
    ),
    _region(
        "middle_east",
        "中东",
        56,
        40,
        "油气与炼化枢纽",
        "原油、天然气、炼化和港口转运能力突出，是全球能源定价与航运关键点。",
        ["crude_oil", "natural_gas", "refinery_fuels", "shipping_ports", "lng_gas"],
        ["Tadawul", "Dubai", "Abu Dhabi"],
    ),
    _region(
        "africa",
        "非洲",
        50,
        60,
        "矿产与新兴消费前沿",
        "铜、镍、稀有矿和区域港口资源丰富，同时承接部分消费升级与基建需求。",
        ["copper_ore", "nickel_ore", "rare_earth_ore", "shipping_ports", "building_construction"],
        ["Johannesburg", "Casablanca"],
    ),
    _region(
        "china",
        "中国",
        78,
        34,
        "制造总装与完整产业链中枢",
        "电网、新能源、半导体应用、消费互联网、物流和金融体系高度协同。",
        [
            "power_grid",
            "solar_power",
            "wind_power",
            "battery_cells",
            "new_energy_vehicle",
            "telecom_equipment",
            "optical_modules",
            "mlcc",
            "high_speed_connectors",
            "industrial_automation",
            "logistics_express",
            "internet_platform",
        ],
        ["上交所", "深交所", "港交所", "上海临港"],
    ),
    _region(
        "developed_asia",
        "日韩台",
        84,
        24,
        "半导体与精密制造高地",
        "晶圆、材料、设备、被动元件和汽车电子链条深厚。",
        [
            "semiconductor_materials",
            "integrated_circuits",
            "hbm_memory",
            "ddr5_memory",
            "nand_flash",
            "enterprise_ssd",
            "gpu_advanced_package",
            "abf_substrate",
            "pcb_fpc",
            "mlcc",
            "display_glass",
            "passive_components",
            "smart_devices",
            "medical_devices",
        ],
        ["TSE", "KRX", "TWSE"],
    ),
    _region(
        "asean",
        "东盟",
        82,
        50,
        "电子制造与航运转口带",
        "承接消费电子组装、港口物流、棕榈油与部分新能源制造转移。",
        ["smart_devices", "enterprise_ssd", "display_glass", "ecommerce_retail", "shipping_ports", "logistics_express", "plastics_rubber"],
        ["SGX", "IDX", "SET", "Singapore"],
    ),
    _region(
        "india",
        "印度",
        70,
        46,
        "增量人口与数字服务市场",
        "软件外包、互联网平台、制药和消费增长快，制造升级正在抬升。",
        ["software_cloud", "internet_platform", "innovative_drugs", "ecommerce_retail", "travel_hospitality"],
        ["NSE", "BSE", "Mumbai"],
    ),
    _region(
        "australia",
        "澳洲",
        90,
        66,
        "矿产与清洁能源资源地",
        "铁矿、锂矿、稀土和 LNG 资源禀赋突出，是亚洲制造链的重要上游。",
        ["iron_ore", "lithium_ore", "rare_earth_ore", "natural_gas", "wind_power"],
        ["ASX", "Perth", "Sydney"],
    ),
]


DEFAULT_FOCUS_NODE_KEY = "ai_compute"


def _validate_seed() -> None:
    if len(CHAIN_LAYERS) != 8:
        raise ValueError("CHAIN_LAYERS must contain 8 layers")

    node_keys = [node["node_key"] for node in CHAIN_NODES]
    if len(node_keys) != len(set(node_keys)):
        raise ValueError("CHAIN_NODES contains duplicate node_key values")
    if not 60 <= len(CHAIN_NODES) <= 120:
        raise ValueError("CHAIN_NODES count is out of expected range")

    valid_layers = set(CHAIN_LAYERS)
    for node in CHAIN_NODES:
        if node["layer"] not in valid_layers:
            raise ValueError(f"unknown layer for node {node['node_key']}")
        for field in ("industry_names", "tags", "anchor_companies", "indicators"):
            if not node[field]:
                raise ValueError(f"node {node['node_key']} missing {field}")

    key_set = set(node_keys)
    if not 100 <= len(CHAIN_EDGES) <= 220:
        raise ValueError("CHAIN_EDGES count is out of expected range")
    for edge in CHAIN_EDGES:
        if edge["source"] not in key_set or edge["target"] not in key_set:
            raise ValueError(f"edge references unknown node: {edge}")

    if not WORLD_REGIONS:
        raise ValueError("WORLD_REGIONS cannot be empty")
    for region in WORLD_REGIONS:
        if not region["node_keys"]:
            raise ValueError(f"region {region['region_key']} missing node mappings")
        missing = [node_key for node_key in region["node_keys"] if node_key not in key_set]
        if missing:
            raise ValueError(f"region {region['region_key']} references unknown nodes: {missing}")

    if DEFAULT_FOCUS_NODE_KEY not in key_set:
        raise ValueError("DEFAULT_FOCUS_NODE_KEY must exist in CHAIN_NODES")


_validate_seed()


__all__ = [
    "CHAIN_LAYERS",
    "CHAIN_NODES",
    "CHAIN_EDGES",
    "WORLD_REGIONS",
    "DEFAULT_FOCUS_NODE_KEY",
]
