export type ChainStage = "commodity" | "material" | "component" | "application" | "service";

export type IndustryChainNode = {
  key: string;
  label: string;
  industryName?: string;
  stage: ChainStage;
  root: string;
  description: string;
  x: number;
  y: number;
};

export type IndustryChainLink = {
  source: string;
  target: string;
  flow: string;
};

export type FocusIndustryChainLink = {
  source: string;
  target: string;
  flow: string;
  weight?: number;
};

export type WorldIndustryRegion = {
  key: string;
  label: string;
  x: number;
  y: number;
  industries: string[];
  specialty: string;
  listedHubs: string[];
};

export const CHAIN_STAGE_LABELS: Record<ChainStage, string> = {
  commodity: "上游大宗",
  material: "材料加工",
  component: "中游部件",
  application: "下游应用",
  service: "数字服务",
};

export const FOCUS_INDUSTRY_CHAIN_LINKS: FocusIndustryChainLink[] = [
  { source: "煤炭", target: "电力电网", flow: "火电燃料 / 电价基准" },
  { source: "油气", target: "电力电网", flow: "天然气发电 / 能源成本" },
  { source: "核电", target: "电力电网", flow: "基荷电力" },
  { source: "电力电网", target: "储能", flow: "消纳调峰" },
  { source: "电力电网", target: "AI算力", flow: "高耗能负载" },
  { source: "电力电网", target: "新能源车", flow: "充换电网络" },
  { source: "电力电网", target: "低空经济", flow: "低空基础设施" },
  { source: "电力电网", target: "互联网平台", flow: "云与数据中心" },
  { source: "煤炭", target: "化工材料", flow: "煤化工原料" },
  { source: "油气", target: "化工材料", flow: "炼化原料" },
  { source: "化工材料", target: "固态电池", flow: "电解质 / 辅材" },
  { source: "化工材料", target: "半导体", flow: "电子化学品" },
  { source: "化工材料", target: "汽车零部件", flow: "轻量化 / 内外饰" },
  { source: "化工材料", target: "纺织服饰", flow: "化纤与染料" },
  { source: "化工材料", target: "包装造纸", flow: "塑料包装 / 涂层" },
  { source: "化工材料", target: "家居消费", flow: "涂料 / 胶黏剂" },
  { source: "黄金", target: "有色金属", flow: "矿业风险偏好" },
  { source: "有色金属", target: "光伏", flow: "银浆 / 铜材 / 铝材" },
  { source: "有色金属", target: "风电", flow: "铜缆 / 铸件" },
  { source: "有色金属", target: "储能", flow: "锂镍钴铜" },
  { source: "有色金属", target: "固态电池", flow: "锂镍钴铜" },
  { source: "有色金属", target: "半导体", flow: "靶材 / 封装金属" },
  { source: "稀土", target: "新能源车", flow: "永磁电机" },
  { source: "稀土", target: "机器人", flow: "伺服电机" },
  { source: "稀土", target: "智能驾驶", flow: "传感与电机" },
  { source: "钢铁", target: "风电", flow: "塔筒 / 铸锻件" },
  { source: "钢铁", target: "工程机械", flow: "设备钢材" },
  { source: "钢铁", target: "高铁轨交", flow: "轨道 / 车辆钢材" },
  { source: "钢铁", target: "建筑建材", flow: "基建地产" },
  { source: "钢铁", target: "汽车零部件", flow: "车身 / 底盘" },
  { source: "光伏", target: "储能", flow: "新能源消纳" },
  { source: "风电", target: "储能", flow: "新能源消纳" },
  { source: "储能", target: "新能源车", flow: "电池技术复用" },
  { source: "固态电池", target: "新能源车", flow: "动力电池" },
  { source: "汽车零部件", target: "新能源车", flow: "供应链" },
  { source: "汽车零部件", target: "智能驾驶", flow: "汽车电子 / 底盘" },
  { source: "新能源车", target: "智能驾驶", flow: "智能化升级" },
  { source: "半导体", target: "AI算力", flow: "GPU / HBM / 服务器" },
  { source: "半导体", target: "通信设备", flow: "芯片 / 模组" },
  { source: "半导体", target: "消费电子", flow: "端侧芯片" },
  { source: "半导体", target: "智能驾驶", flow: "智驾芯片" },
  { source: "半导体", target: "医疗器械", flow: "影像 / IVD 芯片" },
  { source: "通信设备", target: "AI算力", flow: "网络互联" },
  { source: "通信设备", target: "低空经济", flow: "通信导航" },
  { source: "AI算力", target: "软件服务", flow: "模型与企业应用" },
  { source: "AI算力", target: "互联网平台", flow: "云服务 / 广告" },
  { source: "AI算力", target: "网络安全", flow: "数据安全" },
  { source: "AI算力", target: "游戏传媒", flow: "内容生成 / 渲染" },
  { source: "软件服务", target: "网络安全", flow: "信创与数据安全" },
  { source: "软件服务", target: "银行", flow: "金融 IT" },
  { source: "软件服务", target: "保险", flow: "金融 IT" },
  { source: "软件服务", target: "券商", flow: "交易与财富管理系统" },
  { source: "消费电子", target: "互联网平台", flow: "终端入口" },
  { source: "消费电子", target: "游戏传媒", flow: "硬件入口" },
  { source: "机器人", target: "工程机械", flow: "工业自动化" },
  { source: "仪器仪表", target: "半导体", flow: "检测设备" },
  { source: "仪器仪表", target: "医疗器械", flow: "检测与诊断" },
  { source: "仪器仪表", target: "机器人", flow: "传感器" },
  { source: "创新药", target: "CXO", flow: "研发外包" },
  { source: "CXO", target: "创新药", flow: "临床与生产服务" },
  { source: "创新药", target: "医疗器械", flow: "院内渠道" },
  { source: "中药", target: "商业零售", flow: "院外渠道" },
  { source: "医疗器械", target: "商业零售", flow: "消费医疗渠道" },
  { source: "农业种业", target: "养殖", flow: "饲料 / 粮食成本" },
  { source: "养殖", target: "食品饮料", flow: "肉禽蛋奶" },
  { source: "农业种业", target: "食品饮料", flow: "粮油原料" },
  { source: "食品饮料", target: "商业零售", flow: "渠道库存" },
  { source: "白酒", target: "商业零售", flow: "渠道与宴席" },
  { source: "食品饮料", target: "旅游酒店", flow: "餐饮消费" },
  { source: "房地产", target: "建筑建材", flow: "地产后周期" },
  { source: "房地产", target: "家居消费", flow: "装修需求" },
  { source: "房地产", target: "家电", flow: "更新与交付" },
  { source: "建筑建材", target: "家居消费", flow: "装修链条" },
  { source: "建筑建材", target: "环保水务", flow: "市政工程" },
  { source: "工程机械", target: "建筑建材", flow: "基建施工" },
  { source: "高铁轨交", target: "交通运输", flow: "运输网络" },
  { source: "航运港口", target: "物流快递", flow: "海运 / 港口" },
  { source: "交通运输", target: "物流快递", flow: "干线运输" },
  { source: "物流快递", target: "跨境电商", flow: "履约网络" },
  { source: "跨境电商", target: "互联网平台", flow: "出海平台" },
  { source: "跨境电商", target: "纺织服饰", flow: "出海品牌" },
  { source: "跨境电商", target: "家居消费", flow: "出海品牌" },
  { source: "交通运输", target: "旅游酒店", flow: "客流恢复" },
  { source: "银行", target: "房地产", flow: "信用周期" },
  { source: "保险", target: "银行", flow: "利率与分红资产" },
  { source: "券商", target: "互联网平台", flow: "交易活跃度 / 财富管理" },
];

export const INDUSTRY_CHAIN_NODES: IndustryChainNode[] = [
  {
    key: "root-power",
    label: "电力",
    stage: "commodity",
    root: "power",
    description: "电源、电网和电力消纳，是高耗能制造与数字基础设施的共同底座。",
    x: 4,
    y: 14,
  },
  {
    key: "root-energy",
    label: "油气/煤炭",
    stage: "commodity",
    root: "energy",
    description: "传统能源、燃料成本和炼化原料，影响化工、电力、运输等链条。",
    x: 4,
    y: 36,
  },
  {
    key: "root-precious",
    label: "贵金属",
    stage: "commodity",
    root: "precious",
    description: "黄金和贵金属资产，更多受实际利率、避险需求和矿企供给影响。",
    x: 4,
    y: 55,
  },
  {
    key: "root-industrial",
    label: "工业金属",
    stage: "commodity",
    root: "industrial",
    description: "铜、铝、锂、镍、稀土和钢铁，是电动化、制造和基建的核心投入。",
    x: 4,
    y: 76,
  },
  {
    key: "root-chemical",
    label: "化工原料",
    stage: "commodity",
    root: "chemical",
    description: "石化、氟化工、聚氨酯和新材料向电池、电子、汽车、家居延伸。",
    x: 4,
    y: 92,
  },
  {
    key: "nuclear",
    label: "核电",
    industryName: "核电",
    stage: "material",
    root: "power",
    description: "核电运营、核岛设备、核燃料和常规岛设备。",
    x: 23,
    y: 6,
  },
  {
    key: "grid",
    label: "电力电网",
    industryName: "电力电网",
    stage: "material",
    root: "power",
    description: "输配电、特高压、变压器、虚拟电厂和配网自动化。",
    x: 23,
    y: 17,
  },
  {
    key: "solar",
    label: "光伏",
    industryName: "光伏",
    stage: "component",
    root: "power",
    description: "硅料、硅片、电池片、组件、逆变器和辅材。",
    x: 39,
    y: 6,
  },
  {
    key: "wind",
    label: "风电",
    industryName: "风电",
    stage: "component",
    root: "power",
    description: "风机、海风、塔筒、叶片、轴承和海缆。",
    x: 39,
    y: 18,
  },
  {
    key: "storage",
    label: "储能",
    industryName: "储能",
    stage: "component",
    root: "power",
    description: "电化学储能、PCS、BMS、户储和电网侧储能。",
    x: 55,
    y: 13,
  },
  {
    key: "coal",
    label: "煤炭",
    industryName: "煤炭",
    stage: "material",
    root: "energy",
    description: "动力煤、焦煤、煤化工和高股息能源资产。",
    x: 23,
    y: 31,
  },
  {
    key: "oil-gas",
    label: "油气",
    industryName: "油气",
    stage: "material",
    root: "energy",
    description: "油气开采、油服、炼化、LNG 和天然气。",
    x: 23,
    y: 43,
  },
  {
    key: "chemical-materials",
    label: "化工材料",
    industryName: "化工材料",
    stage: "material",
    root: "chemical",
    description: "化工新材料、氟化工、聚氨酯、钛白粉和周期化工。",
    x: 40,
    y: 39,
  },
  {
    key: "gold",
    label: "黄金",
    industryName: "黄金",
    stage: "material",
    root: "precious",
    description: "黄金矿企、贵金属、避险资产和实际利率。",
    x: 23,
    y: 55,
  },
  {
    key: "nonferrous",
    label: "有色金属",
    industryName: "有色金属",
    stage: "material",
    root: "industrial",
    description: "铜、铝、锂、钴、镍等工业金属和能源金属。",
    x: 23,
    y: 69,
  },
  {
    key: "rare-earth",
    label: "稀土",
    industryName: "稀土",
    stage: "material",
    root: "industrial",
    description: "稀土矿、磁材、永磁电机和战略资源。",
    x: 23,
    y: 82,
  },
  {
    key: "steel",
    label: "钢铁",
    industryName: "钢铁",
    stage: "material",
    root: "industrial",
    description: "普钢、特钢、钢材加工和钢铁周期。",
    x: 40,
    y: 78,
  },
  {
    key: "solid-battery",
    label: "固态电池",
    industryName: "固态电池",
    stage: "component",
    root: "industrial",
    description: "固态电池、锂电材料、设备与验证产线。",
    x: 57,
    y: 58,
  },
  {
    key: "semiconductor",
    label: "半导体",
    industryName: "半导体",
    stage: "component",
    root: "industrial",
    description: "半导体设计、制造、封测、材料、设备和 EDA。",
    x: 58,
    y: 36,
  },
  {
    key: "communication",
    label: "通信设备",
    industryName: "通信设备",
    stage: "component",
    root: "industrial",
    description: "通信设备、光纤光缆、交换机、运营商设备和网络基础设施。",
    x: 74,
    y: 27,
  },
  {
    key: "ai-compute",
    label: "AI算力",
    industryName: "AI算力",
    stage: "application",
    root: "power",
    description: "AI 服务器、光模块、CPO、液冷和算力基础设施。",
    x: 89,
    y: 24,
  },
  {
    key: "consumer-electronics",
    label: "消费电子",
    industryName: "消费电子",
    stage: "application",
    root: "industrial",
    description: "手机、PC、可穿戴、端侧 AI 和电子零部件。",
    x: 78,
    y: 41,
  },
  {
    key: "ev",
    label: "新能源车",
    industryName: "新能源车",
    stage: "application",
    root: "industrial",
    description: "整车、动力电池、热管理、智能座舱和供应链。",
    x: 75,
    y: 59,
  },
  {
    key: "auto-parts",
    label: "汽车零部件",
    industryName: "汽车零部件",
    stage: "component",
    root: "industrial",
    description: "汽车电子、轻量化、底盘、内外饰和零部件供应链。",
    x: 67,
    y: 73,
  },
  {
    key: "smart-driving",
    label: "智能驾驶",
    industryName: "智能驾驶",
    stage: "application",
    root: "industrial",
    description: "自动驾驶、智驾芯片、激光雷达、Robotaxi 和车路协同。",
    x: 91,
    y: 59,
  },
  {
    key: "robotics",
    label: "机器人",
    industryName: "机器人",
    stage: "application",
    root: "industrial",
    description: "人形机器人、工业机器人、传感器、执行器和减速器。",
    x: 87,
    y: 77,
  },
  {
    key: "machinery",
    label: "工程机械",
    industryName: "工程机械",
    stage: "application",
    root: "industrial",
    description: "挖机、起重机、高空作业平台、出海和更新周期。",
    x: 60,
    y: 90,
  },
  {
    key: "building",
    label: "建筑建材",
    industryName: "建筑建材",
    stage: "application",
    root: "industrial",
    description: "建筑工程、水泥、玻璃、陶瓷、装饰材料和基建链条。",
    x: 48,
    y: 96,
  },
  {
    key: "software",
    label: "软件服务",
    industryName: "软件服务",
    stage: "service",
    root: "power",
    description: "企业软件、AI 应用、SaaS 和行业数字化。",
    x: 96,
    y: 10,
  },
  {
    key: "platform",
    label: "互联网平台",
    industryName: "互联网平台",
    stage: "service",
    root: "industrial",
    description: "电商、本地生活、广告、云服务和平台经济。",
    x: 94,
    y: 39,
  },
  {
    key: "security",
    label: "网络安全",
    industryName: "网络安全",
    stage: "service",
    root: "power",
    description: "网络安全、数据安全、信创安全和云安全。",
    x: 94,
    y: 49,
  },
];

export const INDUSTRY_CHAIN_LINKS: IndustryChainLink[] = [
  { source: "root-power", target: "nuclear", flow: "电源供给" },
  { source: "root-power", target: "grid", flow: "输配电" },
  { source: "nuclear", target: "grid", flow: "基荷电力" },
  { source: "grid", target: "storage", flow: "消纳调节" },
  { source: "solar", target: "storage", flow: "新能源消纳" },
  { source: "wind", target: "storage", flow: "新能源消纳" },
  { source: "grid", target: "ai-compute", flow: "高耗能负载" },
  { source: "grid", target: "ev", flow: "充换电网络" },
  { source: "root-energy", target: "coal", flow: "燃料" },
  { source: "root-energy", target: "oil-gas", flow: "燃料与原料" },
  { source: "coal", target: "grid", flow: "火电成本" },
  { source: "oil-gas", target: "chemical-materials", flow: "炼化原料" },
  { source: "root-chemical", target: "chemical-materials", flow: "材料平台" },
  { source: "chemical-materials", target: "solid-battery", flow: "电解质/辅材" },
  { source: "chemical-materials", target: "semiconductor", flow: "电子材料" },
  { source: "chemical-materials", target: "auto-parts", flow: "轻量化/内饰" },
  { source: "root-precious", target: "gold", flow: "矿产资产" },
  { source: "root-industrial", target: "nonferrous", flow: "基础金属" },
  { source: "root-industrial", target: "rare-earth", flow: "战略资源" },
  { source: "root-industrial", target: "steel", flow: "黑色金属" },
  { source: "nonferrous", target: "solid-battery", flow: "锂镍钴铜" },
  { source: "nonferrous", target: "solar", flow: "硅片/银浆/铜" },
  { source: "nonferrous", target: "wind", flow: "铜缆/铸件" },
  { source: "nonferrous", target: "semiconductor", flow: "靶材/封装" },
  { source: "rare-earth", target: "ev", flow: "永磁电机" },
  { source: "rare-earth", target: "robotics", flow: "伺服电机" },
  { source: "steel", target: "wind", flow: "塔筒/铸锻件" },
  { source: "steel", target: "auto-parts", flow: "车身/零部件" },
  { source: "steel", target: "machinery", flow: "设备钢材" },
  { source: "steel", target: "building", flow: "基建地产" },
  { source: "solid-battery", target: "ev", flow: "动力电池" },
  { source: "semiconductor", target: "communication", flow: "芯片/模组" },
  { source: "semiconductor", target: "ai-compute", flow: "GPU/HBM/服务器" },
  { source: "semiconductor", target: "consumer-electronics", flow: "端侧芯片" },
  { source: "semiconductor", target: "smart-driving", flow: "智驾芯片" },
  { source: "communication", target: "ai-compute", flow: "网络互联" },
  { source: "ai-compute", target: "software", flow: "模型与应用" },
  { source: "ai-compute", target: "platform", flow: "云服务/广告" },
  { source: "software", target: "security", flow: "数据与信创" },
  { source: "consumer-electronics", target: "platform", flow: "终端入口" },
  { source: "auto-parts", target: "ev", flow: "供应链" },
  { source: "ev", target: "smart-driving", flow: "智能化" },
  { source: "rare-earth", target: "smart-driving", flow: "传感与电机" },
  { source: "robotics", target: "machinery", flow: "工业自动化" },
];

export const WORLD_INDUSTRY_REGIONS: WorldIndustryRegion[] = [
  {
    key: "north-america",
    label: "北美",
    x: 205,
    y: 165,
    industries: ["AI算力", "软件服务", "网络安全", "半导体", "通信设备", "油气", "黄金", "新能源车", "智能驾驶", "创新药", "医疗器械", "CXO", "银行", "保险", "券商", "游戏传媒", "互联网平台", "跨境电商", "商业零售"],
    specialty: "云计算、油气、半导体设计、医药和大型平台",
    listedHubs: ["美股", "加拿大矿业", "大型科技平台"],
  },
  {
    key: "latin-america",
    label: "拉美",
    x: 285,
    y: 360,
    industries: ["有色金属", "黄金", "农业种业", "养殖", "食品饮料", "油气", "煤炭", "航运港口"],
    specialty: "铜、锂、黄金、农产品、油气和航运",
    listedHubs: ["铜矿", "锂盐湖", "农业资源"],
  },
  {
    key: "europe",
    label: "欧洲",
    x: 490,
    y: 155,
    industries: ["电力电网", "风电", "核电", "储能", "汽车零部件", "工程机械", "高铁轨交", "创新药", "医疗器械", "CXO", "银行", "保险", "券商", "旅游酒店", "商业零售", "家电"],
    specialty: "电网、海风、核电、汽车、医药和消费服务",
    listedHubs: ["欧股设备商", "公用事业", "汽车供应链"],
  },
  {
    key: "middle-east",
    label: "中东",
    x: 575,
    y: 245,
    industries: ["油气", "化工材料", "电力电网", "光伏", "储能", "建筑建材", "旅游酒店", "航运港口", "交通运输"],
    specialty: "油气、炼化、化工、电力投资和基建",
    listedHubs: ["能源央企", "炼化平台", "主权投资链"],
  },
  {
    key: "africa",
    label: "非洲",
    x: 510,
    y: 330,
    industries: ["黄金", "有色金属", "油气", "稀土", "煤炭", "农业种业", "养殖", "交通运输"],
    specialty: "金矿、铜钴、油气、农产品和战略矿产",
    listedHubs: ["黄金矿企", "铜钴矿", "油气资源"],
  },
  {
    key: "china",
    label: "中国",
    x: 725,
    y: 235,
    industries: ["新能源车", "智能驾驶", "汽车零部件", "光伏", "风电", "储能", "固态电池", "半导体", "AI算力", "通信设备", "消费电子", "机器人", "低空经济", "军工信息化", "有色金属", "稀土", "钢铁", "化工材料", "电力电网", "核电", "软件服务", "网络安全", "互联网平台", "跨境电商", "物流快递", "航运港口", "建筑建材", "工程机械", "高铁轨交", "环保水务", "农业种业", "养殖", "食品饮料", "白酒", "中药", "医疗器械", "CXO", "银行", "保险", "券商", "房地产", "家电", "游戏传媒", "纺织服饰", "商业零售", "旅游酒店", "交通运输", "仪器仪表", "包装造纸", "家居消费", "综合行业"],
    specialty: "新能源制造、储能、光伏、稀土、电网设备和全产业链配套",
    listedHubs: ["A股", "港股", "新能源供应链"],
  },
  {
    key: "japan-korea",
    label: "日韩",
    x: 805,
    y: 210,
    industries: ["半导体", "消费电子", "汽车零部件", "新能源车", "智能驾驶", "机器人", "通信设备", "游戏传媒", "医疗器械", "化工材料", "仪器仪表"],
    specialty: "存储、消费电子、汽车供应链、机器人和材料",
    listedHubs: ["半导体材料", "整车供应链", "自动化设备"],
  },
  {
    key: "southeast-asia",
    label: "东南亚/印度",
    x: 735,
    y: 330,
    industries: ["消费电子", "跨境电商", "纺织服饰", "新能源车", "光伏", "半导体", "家电", "家居消费", "物流快递", "航运港口", "交通运输", "旅游酒店", "食品饮料", "互联网平台"],
    specialty: "电子组装、服装、跨境电商、制造迁移和旅游消费",
    listedHubs: ["制造基地", "平台出海", "供应链服务"],
  },
  {
    key: "australia",
    label: "澳洲",
    x: 815,
    y: 405,
    industries: ["有色金属", "煤炭", "黄金", "稀土", "钢铁", "油气", "农业种业", "食品饮料", "航运港口"],
    specialty: "铁矿、煤炭、锂、黄金、油气和农业资源",
    listedHubs: ["矿业公司", "锂矿", "煤炭出口"],
  },
];
